// ♒ Aquarius — anomaly, technology, rule-breaking, independence.
import { entry } from "./define.ts";

export const AQUARIUS = [
  entry("INTJ", "System Architect", {
    name: "Rewrite the Rules",
    type: "ACTIVE",
    description: "Choose one rule change for this round: +1 to every roll, +1 action point for everyone, or Fate can add up to 3 to a roll.",
    tags: ["rules"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "MODIFY_RULE", rule: "CHOSEN_NUMERIC_RULE", delta: 1, rounds: 1 }],
  }),
  entry("INTP", "Quantum Recluse", {
    name: "Superposition",
    type: "REACTION",
    description: "One of your rolls produces two results. Choose which one counts before it resolves.",
    tags: ["roll", "reroll"],
    trigger: { on: "OWN_ROLL_RESOLVED" },
    target: "SELF",
    effects: [{ kind: "REROLL", who: "SELF", keep: "CHOOSE" }],
  }),
  entry("ENTJ", "Future Autocrat", {
    name: "System Update",
    type: "ACTIVE",
    description: "Next round, a random rule change applies to everyone.",
    tags: ["rules", "group"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "DELAY_EFFECT", rounds: 1, effects: [{ kind: "MODIFY_RULE", rule: "RANDOM_GLOBAL_MODIFIER", delta: 1, rounds: 1 }] }],
  }),
  entry("ENTP", "Bug Maker", {
    name: "Throw an Error",
    type: "REACTION",
    description: "When a public event is revealed, every loss or Collapse rise it causes is 1 smaller.",
    tags: ["event", "rules"],
    trigger: { on: "EVENT_REVEALED" },
    target: "NONE",
    effects: [{ kind: "MODIFY_EVENT", change: "REMOVE_CONDITION" }],
  }),
  entry("INFJ", "Future Observer", {
    name: "Time Cache",
    type: "ACTIVE",
    description: "See the value of your next roll in advance.",
    tags: ["information", "roll"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "PREVIEW_ROLL", who: "SELF", which: "NEXT_ROUND_FIRST" }],
  }),
  entry("INFP", "Galactic Oddity", {
    name: "Not From Here",
    type: "ACTIVE",
    description: "You will shrug off the next negative effect that hits most of the table.",
    tags: ["defence", "immunity"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "IMMUNITY", who: "SELF", scope: "GROUP_NEGATIVE", rounds: 99, charges: 1 }],
  }),
  entry("ENFJ", "Human Upgrader", {
    name: "Patch",
    type: "ACTIVE",
    description: "Give a chosen player a random small positive status.",
    tags: ["support", "status"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "ADD_STATUS", who: "TARGET", status: "MINOR_BUFF", rounds: 2, random: true }],
  }),
  entry("ENFP", "Cosmic Brainstormer", {
    name: "Anything Goes",
    type: "ACTIVE",
    description: "Draw a random legal ability from the copyable pool of all 192 characters and use it at once.",
    tags: ["copy", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "COPY_EFFECT", source: "RANDOM_ROSTER" }],
    copyable: false,
  }),
  entry("ISTJ", "Protocol Admin", {
    name: "Version Rollback",
    type: "ACTIVE",
    description: "Restore your ordinary statuses to how they were at the end of last round.",
    tags: ["status", "restore"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "ROLLBACK_STATE", who: "SELF", to: "LAST_ROUND_END" }],
  }),
  entry("ISFJ", "Human Firewall", {
    name: "Access Denied",
    type: "REACTION",
    description: "Refuse one ordinary ability another player uses directly on you.",
    tags: ["defence", "cancel"],
    trigger: { on: "TARGETED_ABILITY_DECLARED" },
    target: "SELF",
    effects: [{ kind: "CANCEL_EFFECT", which: "INCOMING" }],
    requires: "ABILITY_TARGETS_SELF",
  }),
  entry("ESTJ", "Server Admin", {
    name: "Hard Reboot",
    type: "ACTIVE",
    description: "Clear every ongoing status in play that is allowed to be cleared.",
    tags: ["status", "cleanse", "group"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "REMOVE_STATUS", who: "ALL", polarity: "ANY", count: "ALL" }],
  }),
  entry("ESFJ", "Social OS", {
    name: "Auto Mesh",
    type: "ACTIVE",
    description: "Three random players are bonded this round. The first reward any of them gains pays each of the others 1 Fate.",
    tags: ["fate", "bond", "group"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    effects: [{ kind: "BOND", between: ["TARGETS"], onFirstReward: 1, rounds: 1 }],
    count: 3,
  }),
  entry("ISTP", "Ghost in the Machine", {
    name: "Go Offline",
    type: "ACTIVE",
    description: "For the rest of this round, ordinary effects from other players can't touch you.",
    tags: ["defence", "immunity"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "IMMUNITY", who: "SELF", scope: "PLAYER_INTERACTION", rounds: 1 }],
  }),
  entry("ISFP", "Neon Drifter", {
    name: "Random Skin",
    type: "ACTIVE",
    description: "Copy one buff a chosen player has, for one round.",
    tags: ["copy", "buff"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_ZODIAC_BUFF", to: "SELF", rounds: 1 }],
  }),
  entry("ESTP", "System Intruder", {
    name: "Hack",
    type: "REACTION",
    description: "Force a player to reroll one of their ordinary rolls.",
    tags: ["roll", "reroll", "disrupt"],
    trigger: { on: "ANY_ROLL_RESOLVED", others: true },
    target: "ANY_PLAYER",
    effects: [{ kind: "REROLL", who: "TRIGGER_SUBJECT", keep: "SECOND" }],
  }),
  entry("ESFP", "Cyber Party Machine", {
    name: "Server Rave",
    type: "ACTIVE",
    description: "This round, several players' unused active abilities are randomly reassigned. Ownership returns next round.",
    tags: ["chaos", "group"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "SHUFFLE_SKILLS", scope: "UNUSED_ACTIVE", rounds: 1 }],
    copyable: false,
  }),
];
