// ♈ Aries — impulse, first strike, attack, burst.
import { entry } from "./define.ts";

export const ARIES = [
  entry("INTJ", "Crimson Strategist", {
    name: "Premeditated Charge",
    type: "REACTION",
    description: "After seeing your own roll, shift the result one tier in your favour.",
    tags: ["roll", "modify"],
    trigger: { on: "OWN_ROLL_RESOLVED" },
    target: "SELF",
    effects: [{ kind: "MODIFY_RESULT", who: "SELF", tiers: 1, toward: "BETTER" }],
  }),
  entry("INTP", "Spark Dismantler", {
    name: "Reignite",
    type: "REACTION",
    description: "After one of your rolls resolves, reroll it once. You must keep the second result.",
    tags: ["roll", "reroll"],
    trigger: { on: "OWN_ROLL_RESOLVED" },
    target: "SELF",
    effects: [{ kind: "REROLL", who: "SELF", keep: "SECOND" }],
  }),
  entry("ENTJ", "Vanguard Marshal", {
    name: "All-Out Charge",
    type: "ACTIVE",
    description: "Choose another player. You and they each gain 1 Fate.",
    tags: ["fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
      { kind: "GAIN_FATE", who: "TARGET", amount: 1 },
    ],
  }),
  entry("ENTP", "Incendiary Sophist", {
    name: "Pass the Blame",
    type: "REACTION",
    description: "When a single-target negative effect is aimed at you, pass it to another random legal player.",
    tags: ["defence", "redirect"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF" },
    target: "RANDOM_PLAYERS",
    effects: [{ kind: "REDIRECT", to: "RANDOM_LEGAL" }],
  }),
  entry("INFJ", "Still-Flame Seer", {
    name: "Omen in the Flame",
    type: "ACTIVE",
    description: "Look at the type of the next public event before it appears.",
    tags: ["information", "preview"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "PREVIEW_EVENT", count: 1, detail: "TYPE", filter: "NEXT_PUBLIC" }],
  }),
  entry("INFP", "Red-Hearted Wanderer", {
    name: "Warm-Blooded Heart",
    type: "PASSIVE",
    description: "The first time you receive a negative effect, reduce its strength by one level.",
    tags: ["defence", "reduce"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF" },
    target: "SELF",
    effects: [{ kind: "REDUCE_EFFECT", levels: 1 }],
  }),
  entry("ENFJ", "Blazing Rallier", {
    name: "Follow Me",
    type: "ACTIVE",
    description: "Bind yourself to another player. This round, whenever either of you gains Fate, the other gains 1.",
    tags: ["fate", "bond"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "BOND", between: ["SELF", "TARGET"], onGainFate: 1, rounds: 1 }],
  }),
  entry("ENFP", "Wildfire Idea Machine", {
    name: "Sudden Sprint",
    type: "ACTIVE",
    description: "Immediately draw an extra small event for yourself.",
    tags: ["event", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "RANDOM_EVENT", size: "SMALL", participants: "SELF" }],
  }),
  entry("ISTJ", "Iron-Rule Vanguard", {
    name: "First-Move Discipline",
    type: "PASSIVE",
    description: "If you are the first passenger to succeed on a roll this round, gain 1 extra Fate.",
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "FIRST_SUCCESS_THIS_ROUND" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  }),
  entry("ISFJ", "Hearth Gatekeeper", {
    name: "Take the Hit",
    type: "REACTION",
    description: "Take a negative effect in place of any player, and reduce its strength.",
    tags: ["defence", "protect", "redirect"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_ANY", others: true },
    target: "TRIGGER_SOURCE",
    effects: [
      { kind: "REDIRECT", to: "SELF" },
      { kind: "REDUCE_EFFECT", levels: 1 },
    ],
  }),
  entry("ESTJ", "War-Banner Executor", {
    name: "Forced Advance",
    type: "ACTIVE",
    description: "Choose a player. They immediately make a free Investigate roll where they stand.",
    tags: ["roll", "tempo"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "FORCE_ROLL", who: "TARGET", roll: "ORDINARY" }],
  }),
  entry("ESFJ", "Bonfire Captain", {
    name: "Warm Everyone Up",
    type: "ACTIVE",
    description: "Choose two players. They each gain 1 Fate.",
    tags: ["fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "GAIN_FATE", who: "TARGETS", amount: 1 }],
  }),
  entry("ISTP", "Molten-Blade Loner", {
    name: "Precise Dodge",
    type: "REACTION",
    description: "Completely cancel one single-target negative effect aimed at you.",
    tags: ["defence", "cancel"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF" },
    target: "SELF",
    effects: [{ kind: "CANCEL_EFFECT", which: "INCOMING" }],
  }),
  entry("ISFP", "Free Soul in Red Flame", {
    name: "Go With Your Gut",
    type: "ACTIVE",
    description: "The train offers two random instant boons. Choose one.",
    tags: ["choice", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "CHOOSE_ONE", from: "RANDOM_TWO", options: [] }],
  }),
  entry("ESTP", "Breakneck Runner", {
    name: "Jump the Gun",
    type: "REACTION",
    description: "Right after another player uses an ability, gain 1 action point.",
    tags: ["tempo", "interrupt"],
    trigger: { on: "SKILL_USED_BY_OTHER" },
    target: "SELF",
    effects: [{ kind: "GAIN_AP", who: "SELF", amount: 1 }],
    copyable: false,
  }),
  entry("ESFP", "Party Igniter", {
    name: "Heat Up the Room",
    type: "ACTIVE",
    description: "Every player makes a small roll. The highest roller and you each gain 1 Fate.",
    tags: ["fate", "group", "roll"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [
      {
        kind: "GROUP_ROLL",
        who: "ALL",
        mode: "HIGHEST_WINS",
        reward: [
          { kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 1 },
          { kind: "GAIN_FATE", who: "SELF", amount: 1 },
        ],
      },
    ],
  }),
];
