// ♋ Cancer — protection, bonds, emotion, family.
import { entry } from "./define.ts";

export const CANCER = [
  entry("INTJ", "Moon Fortress Planner", {
    name: "Safe House",
    type: "ACTIVE",
    description: "Choose a player. This round, they can't be the target of other players' negative active abilities.",
    tags: ["defence", "protect"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "IMMUNITY", who: "TARGET", scope: "PLAYER_TARGETING", rounds: 1 }],
  }),
  entry("INTP", "Seashell Scholar", {
    name: "Into the Shell",
    type: "ACTIVE",
    description: "Give up the rest of your actions this round. You are immune to negative effects until the round ends.",
    tags: ["defence"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "IMMUNITY", who: "SELF", scope: "NEGATIVE", rounds: 1, charges: 99 }, { kind: "GAIN_AP", who: "SELF", amount: -3 }],
  }),
  entry("ENTJ", "Family Helmsman", {
    name: "Close Ranks",
    type: "REACTION",
    description: "When a teammate receives a negative effect, cancel it. You gain 1 Fate.",
    tags: ["defence", "protect", "fate"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_ANY", others: true },
    target: "TRIGGER_SOURCE",
    effects: [
      { kind: "CANCEL_EFFECT", which: "INCOMING" },
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
    ],
  }),
  entry("ENTP", "Mood Rebounder", {
    name: "Now You Feel It",
    type: "REACTION",
    description: "When a player gives you a negative status, they receive a weaker version of it too.",
    tags: ["counter", "status"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF", fromPlayer: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "COPY_EFFECT", source: "INCOMING", to: "TRIGGER_SOURCE", weaken: true }],
  }),
  entry("INFJ", "Tide Watcher", {
    name: "Mood Forecast",
    type: "ACTIVE",
    description: "Learn whether next round's public event leans toward reward, crisis or a mix.",
    tags: ["information", "preview"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "PREVIEW_EVENT", count: 1, detail: "BIAS", filter: "NEXT_PUBLIC" }],
  }),
  entry("INFP", "Moon-Bay Dreamcatcher", {
    name: "A Hug",
    type: "ACTIVE",
    description: "You and the player with the least Fate each gain 1 Fate.",
    tags: ["fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "LOWEST_FATE",
    effects: [
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
      { kind: "GAIN_FATE", who: "LOWEST_FATE", amount: 1 },
    ],
  }),
  entry("ENFJ", "Moonlit Banquet Host", {
    name: "One Family",
    type: "ACTIVE",
    description: "Form a temporary group of up to three players. This round, each group member's first reward gains +1.",
    tags: ["reward", "group"],
    trigger: { on: "OWN_TURN" },
    target: "UP_TO_THREE_PLAYERS",
    effects: [{ kind: "BONUS_ON_NEXT_REWARD", who: "TARGETS", amount: 1, scope: "FIRST_THIS_ROUND" }],
  }),
  entry("ENFP", "Bubble Comforter", {
    name: "Cheer Up",
    type: "ACTIVE",
    description: "Clear one ordinary negative status from a random player.",
    tags: ["cleanse", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    effects: [{ kind: "REMOVE_STATUS", who: "RANDOM_PLAYER", polarity: "NEGATIVE", count: 1, ordinaryOnly: true }],
  }),
  entry("ISTJ", "Old House Doorkeeper", {
    name: "House Rules",
    type: "PASSIVE",
    description: "After two rounds in a row without actively attacking another player, gain 2 Fate.",
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "NO_ATTACK_2_ROUNDS" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
  }),
  entry("ISFJ", "Quilt Warder", {
    name: "Tuck In",
    type: "ACTIVE",
    description: "Give a player one shield.",
    tags: ["defence", "shield"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "SHIELD", who: "TARGET", charges: 1 }],
  }),
  entry("ESTJ", "Household Disciplinarian", {
    name: "Come Home",
    type: "REACTION",
    description: "When an ability that would move Fate, items or statuses between players is declared, cancel it.",
    tags: ["cancel"],
    trigger: { on: "TARGETED_ABILITY_DECLARED" },
    target: "NONE",
    effects: [{ kind: "CANCEL_EFFECT", which: "PENDING_TRANSFER" }],
    requires: "PENDING_ABILITY_MOVES_RESOURCES",
  }),
  entry("ESFJ", "Mother of the Table", {
    name: "Nobody Left Out",
    type: "ACTIVE",
    description: "The two players with the least Fate each gain 1 Fate.",
    tags: ["fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "LOWEST_FATE",
    effects: [{ kind: "GAIN_FATE", who: "TWO_LOWEST_FATE", amount: 1 }],
  }),
  entry("ISTP", "Hermit-Crab Tinkerer", {
    name: "Swap Shells",
    type: "REACTION",
    description: "When a negative effect is aimed at you, give up one of your buffs to cancel it.",
    tags: ["defence", "status", "swap"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF" },
    target: "SELF",
    effects: [{ kind: "SWAP_STATE", between: ["SELF", "SELF"], what: "STATUS_FOR_STATUS" }],
    requires: "HAS_OTHER_TEMP_STATUS",
  }),
  entry("ISFP", "Moonlight Pillow Beast", {
    name: "Soft Response",
    type: "PASSIVE",
    description: "When another player helps you, you and that player each gain 1 Fate.",
    tags: ["fate", "help"],
    trigger: { on: "HELPED_BY_PLAYER" },
    target: "TRIGGER_SOURCE",
    effects: [
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
      { kind: "GAIN_FATE", who: "TRIGGER_SOURCE", amount: 1 },
    ],
  }),
  entry("ESTP", "Surf Lifeguard", {
    name: "Pull You Back",
    type: "REACTION",
    description: "When another player fails a roll, let them reroll it immediately.",
    tags: ["roll", "reroll", "support"],
    trigger: { on: "ANY_ROLL_RESOLVED", tiers: ["DISASTER", "FAIL"], others: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "REROLL", who: "TRIGGER_SUBJECT", keep: "SECOND" }],
  }),
  entry("ESFP", "Seaside Party Starter", {
    name: "Rising Tide",
    type: "ACTIVE",
    description: "Choose three random players. This round, the first reward each of them gains is +1.",
    tags: ["reward", "group"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    effects: [{ kind: "BONUS_ON_NEXT_REWARD", who: "TARGETS", amount: 1, scope: "FIRST_THIS_ROUND" }],
    count: 3,
  }),
];
