// ♑ Capricorn — growth, accumulation, goals, patience.
import { entry } from "./define.ts";

export const CAPRICORN = [
  entry("INTJ", "Summit Planner", {
    name: "Long-Term Goal",
    type: "ACTIVE",
    description: "Secretly draw a goal for the next three rounds. If you meet it, gain 3 Fate.",
    tags: ["fate", "task", "secret"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "SET_TASK", who: "SELF", rounds: 3, reward: [{ kind: "GAIN_FATE", who: "SELF", amount: 3 }], secret: true }],
  }),
  entry("INTP", "Ridge Calculator", {
    name: "Optimal Route",
    type: "ACTIVE",
    description: "See the value of your next roll before you decide what to do.",
    tags: ["information", "planning"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "PREVIEW_ROLL", who: "SELF", which: "NEXT_ROUND_FIRST" }],
  }),
  entry("ENTJ", "Summit Executive", {
    name: "KPI",
    type: "ACTIVE",
    description: "Set another player a goal. If they meet it by the end of next round, you and they each gain 1 Fate.",
    tags: ["fate", "task", "support"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [
      {
        kind: "SET_TASK",
        who: "TARGET",
        rounds: 1,
        reward: [
          { kind: "GAIN_FATE", who: "SELF", amount: 1 },
          { kind: "GAIN_FATE", who: "TARGET", amount: 1 },
        ],
      },
    ],
  }),
  entry("ENTP", "Capital Climber", {
    name: "Leverage",
    type: "ACTIVE",
    description: "Spend 1 Fate to restore another player's ability that is already used.",
    tags: ["restore", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "RESTORE_SKILL", who: "TARGET", cost: { fate: 1 } }],
    requires: "TARGET_ABILITY_BURNED",
    copyable: false,
  }),
  entry("INFJ", "Summit Watcher", {
    name: "Plan Ahead",
    type: "ACTIVE",
    description: "Place a single-use shield on yourself that is ready from next round.",
    tags: ["defence", "shield"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "SHIELD", who: "SELF", charges: 1, fromRound: "NEXT" }],
  }),
  entry("INFP", "Snowline Wanderer", {
    name: "Slow and Steady",
    type: "PASSIVE",
    description: "If you go two rounds in a row without using an active ability, gain 2 Fate.",
    tags: ["fate", "condition", "patience"],
    trigger: { on: "CONDITION_MET", condition: "NO_ACTIVE_ABILITY_2_ROUNDS" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
  }),
  entry("ENFJ", "Rope Leader", {
    name: "Lend a Hand",
    type: "REACTION",
    description: "When the player with the least Fate succeeds on a roll, you and they each gain 1 extra Fate.",
    tags: ["fate", "support"],
    trigger: { on: "ANY_ROLL_RESOLVED", tiers: ["SUCCESS", "PERFECT"] },
    target: "LOWEST_FATE",
    effects: [
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
      { kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 1 },
    ],
    requires: "SUBJECT_HAS_LOWEST_FATE",
  }),
  entry("ENFP", "Peak Dreamer", {
    name: "Career Change",
    type: "ACTIVE",
    description: "Draw a random active ability from a character of another sign and use it at once.",
    tags: ["copy", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "COPY_EFFECT", source: "RANDOM_OTHER_ZODIAC" }],
    copyable: false,
  }),
  entry("ISTJ", "Time Bookkeeper", {
    name: "Compound Interest",
    type: "PASSIVE",
    description: "After two successes in a row, your next success gains 1 extra Fate.",
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "TWO_CONSECUTIVE_SUCCESSES" },
    target: "SELF",
    effects: [{ kind: "BONUS_ON_NEXT_REWARD", who: "SELF", amount: 1 }],
  }),
  entry("ISFJ", "Base Camp Keeper", {
    name: "Safety Rope",
    type: "ACTIVE",
    description: "Choose a player. Their next failure costs them no resources.",
    tags: ["defence", "support"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "NEGATE_PENALTY", who: "TARGET", also: "KEEP_RESOURCES" }],
  }),
  entry("ESTJ", "Project Lead", {
    name: "Deadline",
    type: "ACTIVE",
    description: "Choose two players. Each makes a free Investigate roll now; whoever succeeds gains 1 extra Fate.",
    tags: ["roll", "fate", "tempo"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "FORCE_ROLL", who: "TARGETS", roll: "ORDINARY", onSuccess: [{ kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 1 }] }],
  }),
  entry("ESFJ", "Team Quartermaster", {
    name: "Team Building",
    type: "PASSIVE",
    description: "Once three different players have succeeded on a roll this round, gain 1 Fate.",
    tags: ["fate", "condition", "group"],
    trigger: { on: "CONDITION_MET", condition: "THREE_PLAYERS_SUCCEEDED_THIS_ROUND" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  }),
  entry("ISTP", "Ice-Wall Engineer", {
    name: "Fixed Anchor",
    type: "ACTIVE",
    description: "Lock your current Fate. It can't be reduced for the rest of this round.",
    tags: ["defence", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "LOCK_FATE", who: "SELF", rounds: 1 }],
  }),
  entry("ISFP", "Snow Sculptor", {
    name: "Something to Show",
    type: "PASSIVE",
    description: "When one of your temporary buffs ends naturally, turn it into 1 Fate.",
    tags: ["fate", "status"],
    trigger: { on: "STATUS_EXPIRING", others: false },
    target: "SELF",
    effects: [{ kind: "CONVERT_STATUS", who: "SELF", into: "FATE", amount: 1 }],
    requires: "EXPIRING_STATUS_IS_OWN_BUFF",
  }),
  entry("ESTP", "Peak Challenger", {
    name: "Summit Push",
    type: "ACTIVE",
    description: "Challenge the player with the most Fate to a contest roll. If you win, gain 2 Fate.",
    tags: ["challenge", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "HIGHEST_FATE",
    effects: [{ kind: "CHALLENGE", against: "TARGET", winnerGains: 2, scope: "SELF_VS_TARGET" }],
  }),
  entry("ESFP", "Summit Celebrator", {
    name: "Victory Party",
    type: "PASSIVE",
    description: "At the end of the round, the last player to succeed on a roll and you each gain 1 Fate.",
    tags: ["fate", "group"],
    trigger: { on: "ROUND_END" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "LAST_SUCCESS", amount: 1 }, { kind: "GAIN_FATE", who: "SELF", amount: 1 }],
    requires: "SOMEONE_SUCCEEDED_THIS_ROUND",
  }),
];
