// ♊ Gemini — copying, information, change, deceit.
import { entry } from "./define.ts";

export const GEMINI = [
  entry("INTJ", "Two-Faced Chessmaster", {
    name: "Identity Swap",
    type: "ACTIVE",
    description: "Swap one swappable temporary status with a chosen player.",
    tags: ["swap", "status"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "SWAP_STATE", between: ["SELF", "TARGET"], what: "TEMP_STATUS" }],
  }),
  entry("INTP", "Ruler of Inner Channels", {
    name: "Copy the Code",
    type: "REACTION",
    description: "Copy the effect of the ability the previous player just used successfully, if it can be copied.",
    tags: ["copy"],
    trigger: { on: "SKILL_USED_BY_OTHER" },
    target: "SELF",
    effects: [{ kind: "COPY_EFFECT", source: "LAST_SKILL", to: "SELF" }],
    copyable: false,
  }),
  entry("ENTJ", "Two-Front Commander", {
    name: "Parallel Tasks",
    type: "ACTIVE",
    description: "Two chosen players each make a quick roll. You choose which result counts; it resolves as an Investigate where that player stands.",
    tags: ["roll", "choice"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "GROUP_ROLL", who: "TARGETS", mode: "PICK_ONE", reward: [] }],
  }),
  entry("ENTP", "Quantum Smooth-Talker", {
    name: "I Never Said That",
    type: "REACTION",
    description: "When everyone has answered a vote or choice, you may change your own answer before it settles.",
    tags: ["choice", "deceit"],
    trigger: { on: "OWN_CHOICE_MADE" },
    target: "SELF",
    effects: [{ kind: "REVISE_CHOICE" }],
  }),
  entry("INFJ", "Mirror-Speech Diviner", {
    name: "Read the Channel",
    type: "ACTIVE",
    description: "Look at one of a chosen player's hidden statuses.",
    tags: ["information", "hidden"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "REVEAL_HIDDEN", who: "TARGET", what: "STATUS" }],
  }),
  entry("INFP", "Two-Sided Sleepwalker", {
    name: "The Other Way",
    type: "REACTION",
    description: "When an either-or event is revealed, you decide it for everyone.",
    tags: ["information", "event"],
    trigger: { on: "CHOICE_EVENT_REVEALED" },
    target: "SELF",
    effects: [{ kind: "MODIFY_EVENT", change: "DECIDER_SELF" }],
  }),
  entry("ENFJ", "Social Router", {
    name: "Rewire",
    type: "ACTIVE",
    description: "Swap the current bonds of two legal players.",
    tags: ["bond", "swap"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "SWAP_STATE", between: ["TARGET", "SECOND_TARGET"], what: "BOND" }],
  }),
  entry("ENFP", "Channel Hopper", {
    name: "Change the Channel",
    type: "REACTION",
    description: "When a replaceable random event appears, generate it again.",
    tags: ["event", "reroll"],
    trigger: { on: "EVENT_REVEALED" },
    target: "NONE",
    effects: [{ kind: "REROLL_EVENT", mode: "SAME_CATEGORY" }],
  }),
  entry("ISTJ", "Double-Ledger Clerk", {
    name: "Backup Copy",
    type: "REACTION",
    description: "Record one of your successful rolls. Later, you can replace one of your ordinary rolls with that result.",
    tags: ["roll", "store"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["SUCCESS", "PERFECT"] },
    target: "SELF",
    effects: [{ kind: "STORE_RESULT", who: "SELF", which: "CURRENT" }],
  }),
  entry("ISFJ", "Secret Messenger", {
    name: "Quiet Warning",
    type: "ACTIVE",
    description: "Choose a player. The next time they fail, they may reroll once.",
    tags: ["roll", "support"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "ADD_STATUS", who: "TARGET", status: "REROLL_NEXT_FAILURE", rounds: 3 }],
  }),
  entry("ESTJ", "Information Dispatcher", {
    name: "Reorder",
    type: "ACTIVE",
    description: "Choose up to three players. Next round they act first, in the order you chose.",
    tags: ["tempo", "turn-order"],
    trigger: { on: "OWN_TURN" },
    target: "UP_TO_THREE_PLAYERS",
    effects: [{ kind: "CHANGE_TURN_ORDER", scope: "NEXT_ROUND" }],
  }),
  entry("ESFJ", "Gossip Relay", {
    name: "Spread the Word",
    type: "REACTION",
    description: "When a player gains a buff, another legal player gains a weaker version of it.",
    tags: ["buff", "copy", "support"],
    trigger: { on: "PLAYER_GAINS_BUFF" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_BUFF", to: "TARGET", weaken: true }],
    copyable: false,
  }),
  entry("ISTP", "Signal Hijacker", {
    name: "Snatch",
    type: "REACTION",
    description: "When another player gains an item as a reward, take it from them.",
    tags: ["item", "steal"],
    trigger: { on: "PLAYER_GAINS_REWARDS", others: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "STEAL_ITEM", from: "TRIGGER_SUBJECT", transferableOnly: true }],
    requires: "REWARD_IS_ITEM",
  }),
  entry("ISFP", "Mirror Drifter", {
    name: "Become You",
    type: "ACTIVE",
    description: "Copy one copyable buff a chosen player has, for one round.",
    tags: ["buff", "copy"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_BUFF", to: "SELF", rounds: 1 }],
    copyable: false,
  }),
  entry("ESTP", "Silver-Tongued Switcher", {
    name: "Switcheroo",
    type: "REACTION",
    description: "When a roll is about to resolve, it takes the best result anyone has rolled this round.",
    tags: ["roll", "swap"],
    trigger: { on: "ANY_ROLL_RESOLVED" },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "SWAP_STATE", between: ["TRIGGER_SUBJECT", "SELF"], what: "ROLL_RESULT" }],
  }),
  entry("ESFP", "Living Comment Stream", {
    name: "All-Channel Broadcast",
    type: "ACTIVE",
    description: "Every player makes a quick secret choice at the same time. Players in the minority gain a reward.",
    tags: ["group", "vote", "reward"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "VOTE", question: "MINORITY_REWARD", reward: [{ kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 1 }] }],
  }),
];
