// ♌ Leo — centre stage, display, leadership, glory.
import { entry } from "./define.ts";

export const LEO = [
  entry("INTJ", "Corona Curator", {
    name: "Lead Role",
    type: "ACTIVE",
    description: "You alone decide the next public event that asks for a choice.",
    tags: ["event"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "MODIFY_EVENT", change: "NEXT_DECIDER" }],
  }),
  entry("INTP", "Throne Watcher", {
    name: "Hidden Protagonist",
    type: "PASSIVE",
    description: "If no other player targets you this round, gain 2 Fate at the end of the round.",
    tags: ["fate", "condition"],
    trigger: { on: "ROUND_END" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
    requires: "NOT_TARGETED_THIS_ROUND",
  }),
  entry("ENTJ", "Golden Tyrant", {
    name: "Do As I Say",
    type: "ACTIVE",
    description: "Choose a player. They move one carriage toward you.",
    tags: ["control"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "MOVE_PLAYER", who: "TARGET", to: "TOWARD_SELF" }],
  }),
  entry("ENTP", "Crown Provocateur", {
    name: "Try Me",
    type: "ACTIVE",
    description: "Challenge any player to roll at the same time as you. The higher result gains 2 Fate.",
    tags: ["challenge", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "CHALLENGE", against: "TARGET", winnerGains: 2, scope: "SELF_VS_TARGET" }],
  }),
  entry("INFJ", "Sacred-Flame Mentor", {
    name: "Spotlight Prophecy",
    type: "ACTIVE",
    description: "Choose a player. Their next roll's rewards are doubled.",
    tags: ["reward", "support"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "DOUBLE_REWARD", who: "TARGET", next: "SUCCESS_REWARD" }],
  }),
  entry("INFP", "Lonely Little Sun", {
    name: "Shine Alone",
    type: "PASSIVE",
    description: "When you are the only player who gains from a public event, gain 1 extra Fate.",
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "SOLE_GAINER_OF_PUBLIC_EVENT" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  }),
  entry("ENFJ", "Sun Summoner", {
    name: "Eyes on Me",
    type: "ACTIVE",
    description: "This round, hostile effects that could target you aim at you first. You also gain one shield.",
    tags: ["defence", "taunt", "shield"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [
      { kind: "ADD_STATUS", who: "SELF", status: "TAUNT", rounds: 1 },
      { kind: "SHIELD", who: "SELF", charges: 1 },
    ],
  }),
  entry("ENFP", "Dazzling Hype Star", {
    name: "Encore",
    type: "PASSIVE",
    description: "After you succeed on a roll two rounds running, draw an extra reward event for yourself.",
    tags: ["event", "reward"],
    trigger: { on: "CONDITION_MET", condition: "SUCCEEDED_TWO_ROUNDS_RUNNING" },
    target: "SELF",
    effects: [{ kind: "RANDOM_EVENT", size: "REWARD", participants: "SELF" }],
  }),
  entry("ISTJ", "Royal Scribe", {
    name: "Record of Deeds",
    type: "PASSIVE",
    description: "On your third successful roll this run, gain 3 extra Fate.",
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "THIRD_SUCCESS_THIS_RUN" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 3 }],
  }),
  entry("ISFJ", "Captain of the Guard", {
    name: "Protect the Crown",
    type: "REACTION",
    description: "Cancel a negative effect on another player. You gain 1 Fate.",
    tags: ["defence", "protect", "fate"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_ANY", others: true },
    target: "TRIGGER_SOURCE",
    effects: [
      { kind: "CANCEL_EFFECT", which: "INCOMING" },
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
    ],
  }),
  entry("ESTJ", "Glory Commander", {
    name: "Fall In",
    type: "ACTIVE",
    description: "Everyone who hasn't acted yet this round goes in order of least Fate first.",
    tags: ["tempo", "turn-order"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "CHANGE_TURN_ORDER", scope: "REMAINING_THIS_ROUND" }],
  }),
  entry("ESFJ", "Red-Carpet Host", {
    name: "Applause",
    type: "ACTIVE",
    description: "A chosen player gains 1 Fate. If another player also helped them this round, you gain 1 Fate too.",
    tags: ["fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "GAIN_FATE", who: "TARGET", amount: 1 }, { kind: "CONDITIONAL", condition: "TARGET_HELPED_BY_ANOTHER_THIS_ROUND", then: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }] }],
  }),
  entry("ISTP", "Golden-Mane Ranger", {
    name: "Grand Entrance",
    type: "PASSIVE",
    description: "Your first failure this run counts as an ordinary success instead.",
    tags: ["roll", "safety"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["DISASTER", "FAIL"] },
    target: "SELF",
    effects: [{ kind: "SET_TIER", who: "SELF", from: ["DISASTER", "FAIL"], to: "SUCCESS" }],
  }),
  entry("ISFP", "Sunset Artist", {
    name: "Graceful Exit",
    type: "REACTION",
    description: "When you gain a reward, give 1 Fate back. Your next roll's rewards are doubled.",
    tags: ["reward", "delay"],
    trigger: { on: "SELF_GAINS_REWARD" },
    target: "SELF",
    effects: [{ kind: "LOSE_FATE", who: "SELF", amount: 1 }, { kind: "DOUBLE_REWARD", who: "SELF", next: "REWARD" }],
  }),
  entry("ESTP", "Arena Star", {
    name: "Duel",
    type: "ACTIVE",
    description: "Call out a player for a contest roll against you. The winner gains 2 Fate.",
    tags: ["challenge", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "CHALLENGE", against: "TARGET", winnerGains: 2, scope: "SELF_VS_TARGET" }],
  }),
  entry("ESFP", "Cosmic Superstar", {
    name: "Centre of Attention",
    type: "ACTIVE",
    description: "Every player votes for one player. That player and you each gain 2 Fate.",
    tags: ["vote", "fate", "group"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [
      {
        kind: "VOTE",
        question: "PICK_PLAYER",
        reward: [
          { kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 2 },
          { kind: "GAIN_FATE", who: "SELF", amount: 2 },
        ],
      },
    ],
  }),
];
