// ♎ Libra — balance, fairness, relationships, choice.
import { entry } from "./define.ts";

export const LIBRA = [
  entry("INTJ", "Equilibrium Arbiter", {
    name: "Level Out",
    type: "ACTIVE",
    description: "Choose two players. Close the Fate gap between them by up to 2.",
    tags: ["fate", "balance"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "BALANCE_FATE", between: ["TARGET", "SECOND_TARGET"], maxStep: 2 }],
  }),
  entry("INTP", "Scale Calculator", {
    name: "Take the Mean",
    type: "REACTION",
    description: "After one of your rolls, roll a second time and use the average of both results, rounded up.",
    tags: ["roll", "reroll"],
    trigger: { on: "OWN_ROLL_RESOLVED" },
    target: "SELF",
    effects: [{ kind: "REROLL", who: "SELF", keep: "AVERAGE" }],
  }),
  entry("ENTJ", "Speaker of Peace", {
    name: "Redistribute",
    type: "ACTIVE",
    description: "Move 1 Fate from the player with the most Fate to the player with the least.",
    tags: ["fate", "balance"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "TRANSFER_FATE", from: "HIGHEST_FATE", to: "LOWEST_FATE", amount: 1 }],
  }),
  entry("ENTP", "Fairness Advocate", {
    name: "Objection",
    type: "REACTION",
    description: "After a public group roll, everyone rolls again before it counts.",
    tags: ["roll", "reroll", "group"],
    trigger: { on: "PUBLIC_ROLL_DONE" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "REROLL", who: "ALL", keep: "SECOND", scope: "ALL" }],
  }),
  entry("INFJ", "Silver-Scale Mediator", {
    name: "Reconcile",
    type: "ACTIVE",
    description: "Choose two players. Each is cleared of one ordinary negative status.",
    tags: ["cancel", "relationship"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "CANCEL_EFFECT", which: "OPPOSITION_STATE" }],
  }),
  entry("INFP", "Moonpale Peacemaker", {
    name: "No Fighting",
    type: "REACTION",
    description: "When another player's ability would harm you, it is cancelled and you each gain 1 Fate instead.",
    tags: ["defence", "convert"],
    trigger: { on: "ATTACKED_BY_PLAYER" },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "CANCEL_EFFECT", which: "INCOMING" }, { kind: "GAIN_FATE", who: "SELF", amount: 1 }, { kind: "GAIN_FATE", who: "TRIGGER_SOURCE", amount: 1 }],
  }),
  entry("ENFJ", "Bond Coordinator", {
    name: "Re-Pair",
    type: "ACTIVE",
    description: "Swap two legal bonds between players.",
    tags: ["bond", "swap"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "SWAP_STATE", between: ["TARGET", "SECOND_TARGET"], what: "BOND" }],
  }),
  entry("ENFP", "Spark Matchmaker", {
    name: "Random Match",
    type: "ACTIVE",
    description: "Bond two random players. This round, the first time either of them succeeds, the other gains 1 Fate.",
    tags: ["bond", "fate", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    effects: [{ kind: "BOND", between: ["TARGETS"], onFirstSuccess: 1, rounds: 1 }],
  }),
  entry("ISTJ", "Codex Assessor", {
    name: "Equal Reward",
    type: "REACTION",
    description: "When a player gains a reward, the player with the least Fate gains the same (up to 2 Fate, or the same item).",
    tags: ["reward", "balance"],
    trigger: { on: "PLAYER_GAINS_REWARDS" },
    target: "NONE",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_REWARD", to: "LOWEST_FATE" }],
  }),
  entry("ISFJ", "White-Feather Peacekeeper", {
    name: "Settle Down",
    type: "REACTION",
    description: "Cancel one attempt by a player to take Fate from another player.",
    tags: ["defence", "cancel", "fate"],
    trigger: { on: "FATE_THEFT_ATTEMPTED" },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "CANCEL_EFFECT", which: "FATE_THEFT" }],
  }),
  entry("ESTJ", "Balance Enforcer", {
    name: "Forced Balance",
    type: "ACTIVE",
    description: "The player with the most Fate loses 1, and the player with the least gains 1.",
    tags: ["fate", "balance"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "BALANCE_FATE", between: ["HIGHEST_FATE", "LOWEST_FATE"], maxStep: 1 }],
  }),
  entry("ESFJ", "Relationship Host", {
    name: "Say Something Nice",
    type: "ACTIVE",
    description: "Choose two players. If they both help each other successfully this round, they each gain 1 Fate.",
    tags: ["bond", "fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "BOND", between: ["TARGET", "SECOND_TARGET"], onMutualHelp: 1, rounds: 1 }],
  }),
  entry("ISTP", "Silent Referee", {
    name: "Void Call",
    type: "REACTION",
    description: "When an ability that would take Fate, Sanity or items from a player is declared, cancel it.",
    tags: ["rules", "cancel"],
    trigger: { on: "TARGETED_ABILITY_DECLARED" },
    target: "NONE",
    effects: [{ kind: "CANCEL_EFFECT", which: "CONFLICTING_ABILITIES" }],
    requires: "PENDING_ABILITY_TAKES",
  }),
  entry("ISFP", "White Rose Traveller", {
    name: "Choose Peace",
    type: "REACTION",
    description: "When a public event is revealed, step out of it and gain 1 Fate.",
    tags: ["event", "fate", "escape"],
    trigger: { on: "EVENT_REVEALED" },
    target: "SELF",
    effects: [
      { kind: "SKIP_EVENT", who: "SELF" },
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
    ],
  }),
  entry("ESTP", "Arena Notary", {
    name: "Fair Duel",
    type: "ACTIVE",
    description: "Choose two players to roll at the same time. The higher roll gains 2 Fate; on a tie, each gains 1.",
    tags: ["contest", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "CHALLENGE", against: "SECOND_TARGET", winnerGains: 2, tieGains: 1, scope: "TWO_TARGETS" }],
  }),
  entry("ESFP", "Queen of the Social Scales", {
    name: "Put It to a Vote",
    type: "REACTION",
    description: "When an everyone-chooses event is revealed, it is settled by a vote instead: the majority's choice applies to everyone.",
    tags: ["event", "vote"],
    trigger: { on: "CHOICE_EVENT_REVEALED" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "VOTE", question: "PICK_OUTCOME" }],
  }),
];
