// ♓ Pisces — dreams, perception, illusion, empathy.
import { entry } from "./define.ts";

export const PISCES = [
  entry("INTJ", "Dream Director", {
    name: "Dream Script",
    type: "ACTIVE",
    description: "Decide whether your next random event leans towards a reward or a challenge.",
    tags: ["event", "planning"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "MODIFY_EVENT", change: "BIAS_CHOSEN" }],
  }),
  entry("INTP", "Illusion Analyst", {
    name: "Is This Real?",
    type: "ACTIVE",
    description: "Look at one hidden effect and decide whether it triggers as written.",
    tags: ["information", "hidden"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "REVEAL_HIDDEN", who: "SELF", what: "EVENT_EFFECT", mayVeto: true }],
  }),
  entry("ENTJ", "Dream-Sea Sovereign", {
    name: "Shared Slumber",
    type: "ACTIVE",
    description: "Choose two players. They and you enter the same random event together.",
    tags: ["event", "group"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "RANDOM_EVENT", size: "STANDARD", participants: "TARGETS" }],
  }),
  entry("ENTP", "Mirage Swindler", {
    name: "Fake Result",
    type: "ACTIVE",
    description: "Show the Inspector a fake result: your next ticket check passes whatever you roll.",
    tags: ["roll", "deception"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "ADD_STATUS", who: "SELF", status: "PASS", rounds: 99, polarity: "POSITIVE" }],
  }),
  entry("INFJ", "Deep-Sea Prophet", {
    name: "Dream Omen",
    type: "ACTIVE",
    description: "See the next public event in full.",
    tags: ["information", "preview"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "PREVIEW_EVENT", count: 1, detail: "FULL", filter: "TARGETING_SELF" }],
  }),
  entry("INFP", "Stargazing Dreamer", {
    name: "Five More Minutes",
    type: "REACTION",
    description: "After you fail a roll, take none of its penalty, and gain 1 extra action point next round.",
    tags: ["roll", "delay"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["FAIL", "DISASTER"] },
    target: "SELF",
    effects: [{ kind: "NEGATE_PENALTY", who: "SELF" }, { kind: "DELAY_EFFECT", rounds: 1, effects: [{ kind: "GAIN_AP", who: "SELF", amount: 1 }] }],
  }),
  entry("ENFJ", "Dream Guide", {
    name: "Shared Dream",
    type: "REACTION",
    description: "When a player gains a buff, give a weaker copy of it to another player.",
    tags: ["support", "copy", "buff"],
    trigger: { on: "PLAYER_GAINS_BUFF" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_BUFF", to: "TARGET", weaken: true }],
  }),
  entry("ENFP", "Bubble Fantasist", {
    name: "Strange Dream",
    type: "REACTION",
    description: "When an event is revealed, randomly change its target, its reward or one non-core condition.",
    tags: ["event", "chaos"],
    trigger: { on: "EVENT_REVEALED" },
    target: "NONE",
    effects: [{ kind: "MODIFY_EVENT", change: "RANDOM_ASPECT" }],
  }),
  entry("ISTJ", "Dream Archivist", {
    name: "Dream Log",
    type: "PASSIVE",
    description: "Your first successful roll is recorded. Later, you may use that result once in place of a roll.",
    tags: ["roll", "store"],
    trigger: { on: "CONDITION_MET", condition: "FIRST_OWN_SUCCESS" },
    target: "SELF",
    effects: [{ kind: "STORE_RESULT", who: "SELF", which: "FIRST_SUCCESS" }],
  }),
  entry("ISFJ", "Deep-Sea Healer", {
    name: "Sleep Easy",
    type: "ACTIVE",
    description: "Clear one ordinary negative status from a chosen player.",
    tags: ["support", "cleanse"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "REMOVE_STATUS", who: "TARGET", polarity: "NEGATIVE", count: 1, ordinaryOnly: true }],
  }),
  entry("ESTJ", "Dream Warden", {
    name: "Wake Up",
    type: "ACTIVE",
    description: "End every rule change in play, and clear one ordinary negative status from each player.",
    tags: ["cancel", "group"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "CANCEL_EFFECT", which: "GLOBAL_EFFECT" }],
  }),
  entry("ESFJ", "Empathic Resonator", {
    name: "I Get You",
    type: "PASSIVE",
    description: "When the player with the least Fate gains a reward, you also gain 1 Fate.",
    tags: ["fate", "support"],
    trigger: { on: "PLAYER_GAINS_REWARDS", others: true },
    target: "LOWEST_FATE",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
    requires: "SUBJECT_HAS_LOWEST_FATE",
  }),
  entry("ISTP", "Subconscious Diver", {
    name: "Dive",
    type: "REACTION",
    description: "Skip the current event if it can be skipped, and stay hidden until the next round begins.",
    tags: ["event", "evade"],
    trigger: { on: "EVENT_REVEALED" },
    target: "SELF",
    effects: [{ kind: "SKIP_EVENT", who: "SELF", hideUntil: "NEXT_ROUND" }],
  }),
  entry("ISFP", "Moon-Sea Painter", {
    name: "Paint the Dream",
    type: "REACTION",
    description: "Turn one of your ordinary successes into a perfect success.",
    tags: ["roll", "modify"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["SUCCESS"] },
    target: "SELF",
    effects: [{ kind: "SET_TIER", who: "SELF", from: ["SUCCESS"], to: "PERFECT" }],
  }),
  entry("ESTP", "Dream-Wave Surfer", {
    name: "Ride the Dream",
    type: "ACTIVE",
    description: "Generate two legal events and take the one with the higher potential reward. You must accept its risk.",
    tags: ["event", "risk"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "RANDOM_EVENT", size: "STANDARD", choices: 2, pick: "HIGHER_REWARD", participants: "SELF" }],
  }),
  entry("ESFP", "Dream Party Sprite", {
    name: "Everybody Dream",
    type: "ACTIVE",
    description: "Every player gains a different random temporary status.",
    tags: ["status", "group", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "ADD_STATUS", who: "ALL", status: "DREAM", rounds: 1, random: true }],
  }),
];
