// ♐ Sagittarius — adventure, distance, chance, freedom.
import { entry } from "./define.ts";

export const SAGITTARIUS = [
  entry("INTJ", "Star-Track Hunter", {
    name: "Long-Range Plan",
    type: "ACTIVE",
    description: "Draw a goal for this round and the next. If you meet it, gain 2 Fate.",
    tags: ["task", "fate", "planning"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "SET_TASK", who: "SELF", rounds: 1, reward: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }] }],
  }),
  entry("INTP", "Cosmic Cartographer", {
    name: "Into the Unknown",
    type: "ACTIVE",
    description: "Choose one of three hidden random events and open it.",
    tags: ["event", "choice"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "RANDOM_EVENT", size: "STANDARD", choices: 3, pick: "CHOOSE", participants: "SELF" }],
  }),
  entry("ENTJ", "Expedition Leader", {
    name: "Move Out",
    type: "ACTIVE",
    description: "Choose two players to join you in an extra multiplayer event.",
    tags: ["event", "group"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "RANDOM_EVENT", size: "MULTI", participants: "TARGETS" }],
  }),
  entry("ENTP", "Cosmic Gambler", {
    name: "High or Low",
    type: "ACTIVE",
    description: "Bet on your next roll: on a success, gain 3 extra Fate; on a failure, lose 1 Fate.",
    tags: ["fate", "risk", "wager"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [
      {
        kind: "WAGER",
        onSuccess: [{ kind: "GAIN_FATE", who: "SELF", amount: 3 }],
        onFail: [{ kind: "LOSE_FATE", who: "SELF", amount: 1 }],
      },
    ],
  }),
  entry("INFJ", "Starpath Seer", {
    name: "See Further",
    type: "ACTIVE",
    description: "Look at the types of the next three public events.",
    tags: ["information", "preview"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "PREVIEW_EVENT", count: 3, detail: "TYPE", filter: "NEXT_PUBLIC" }],
  }),
  entry("INFP", "Wandering Star Poet", {
    name: "Free Route",
    type: "REACTION",
    description: "When a public event is revealed, step out of it and draw an extra event for yourself instead.",
    tags: ["event", "escape"],
    trigger: { on: "EVENT_REVEALED" },
    target: "SELF",
    effects: [{ kind: "SKIP_EVENT", who: "SELF", reroute: true }],
  }),
  entry("ENFJ", "Quest Caller", {
    name: "Come Along",
    type: "REACTION",
    description: "When you gain a reward, a chosen player gains the same (up to 2 Fate, or the same item).",
    tags: ["event", "support", "reward"],
    trigger: { on: "SELF_GAINS_REWARD" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_REWARD", to: "TARGET" }],
  }),
  entry("ENFP", "Boundless Adventurer", {
    name: "Random Warp",
    type: "ACTIVE",
    description: "Draw an extra group-roll event for yourself.",
    tags: ["event", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "RANDOM_EVENT", size: "MINIGAME", participants: "SELF" }],
  }),
  entry("ISTJ", "Expedition Logkeeper", {
    name: "Check In",
    type: "PASSIVE",
    description: "Succeed on three different kinds of roll (Investigate, Search, Repair, Confront) and gain 2 Fate.",
    tags: ["fate", "condition", "counter"],
    trigger: { on: "CONDITION_MET", condition: "THREE_ROLL_KINDS" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
  }),
  entry("ISFJ", "Caravan Quartermaster", {
    name: "Supply Pack",
    type: "ACTIVE",
    description: "Give yourself or a teammate one random single-use buff.",
    tags: ["item", "support"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "GRANT_ITEM", who: "TARGET", pool: "BUFF", count: 1 }],
  }),
  entry("ESTJ", "Frontier Commander", {
    name: "New Map",
    type: "REACTION",
    description: "Replace the current public event, if it can be replaced, with an event from a different category.",
    tags: ["event", "control"],
    trigger: { on: "EVENT_REVEALED" },
    target: "NONE",
    effects: [{ kind: "REROLL_EVENT", mode: "OTHER_CATEGORY" }],
  }),
  entry("ESFJ", "Tour Group Leader", {
    name: "Group Tour",
    type: "ACTIVE",
    description: "Choose up to three players to roll together. If their total reaches 4 per player, each of them gains 1 Fate.",
    tags: ["group", "roll", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "UP_TO_THREE_PLAYERS",
    effects: [{ kind: "GROUP_ROLL", who: "TARGETS", mode: "SUM_THRESHOLD", reward: [{ kind: "GAIN_FATE", who: "TARGETS", amount: 1 }] }],
  }),
  entry("ISTP", "Wilderness Escapist", {
    name: "Bail Out",
    type: "REACTION",
    description: "When you fail a roll, take none of its penalty.",
    tags: ["event", "escape", "defence"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["DISASTER", "FAIL"] },
    target: "SELF",
    effects: [{ kind: "NEGATE_PENALTY", who: "SELF", also: "EXIT_EVENT" }],
  }),
  entry("ISFP", "Galaxy Photographer", {
    name: "Capture the Moment",
    type: "PASSIVE",
    description: "Whenever you roll an extreme 1 or 6, gain 1 Fate.",
    tags: ["fate", "roll", "condition"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["DISASTER", "PERFECT"] },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
    requires: "RAW_ROLL_1_OR_6",
  }),
  entry("ESTP", "Bungee Daredevil", {
    name: "All In",
    type: "ACTIVE",
    description: "Your next roll counts double: rewards and penalties alike.",
    tags: ["reward", "risk"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "DOUBLE_REWARD", who: "SELF", next: "REWARD", penaltyToo: true }],
  }),
  entry("ESFP", "Cosmic Tour Bus", {
    name: "Mystery Destination",
    type: "ACTIVE",
    description: "Split all players into two random groups, each entering a different small public event.",
    tags: ["event", "group", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "RANDOM_EVENT", size: "SMALL", participants: "ALL", split: "TWO_GROUPS" }],
  }),
];
