// ♏ Scorpio — secrets, reversal, control, revenge.
import { entry } from "./define.ts";

export const SCORPIO = [
  entry("INTJ", "Abyssal Puppeteer", {
    name: "Hidden Thread",
    type: "ACTIVE",
    description: "Secretly choose another player. The next time they gain a reward, you gain 1 Fate.",
    tags: ["fate", "secret", "bond"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "BOND", between: ["TARGET", "SELF"], onFirstReward: 1, rounds: 12, secret: true, oneWay: true }],
  }),
  entry("INTP", "Forbidden Zone Decoder", {
    name: "Crack It",
    type: "ACTIVE",
    description: "See the next public event in full.",
    tags: ["information", "hidden"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "REVEAL_HIDDEN", who: "SELF", what: "EVENT_EFFECT" }],
  }),
  entry("ENTJ", "Obsidian Overlord", {
    name: "Dominate",
    type: "ACTIVE",
    description: "Choose another player. Their next active ability can't target you.",
    tags: ["control", "defence"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "FORBID_TARGETING", who: "TARGET", protects: "SELF", uses: 1 }],
  }),
  entry("ENTP", "The Venom-Tongued Schemer", {
    name: "Backbite",
    type: "REACTION",
    description: "After another player puts a negative effect on you, make that player take a risk roll.",
    tags: ["revenge", "roll"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF", fromPlayer: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "FORCE_ROLL", who: "TRIGGER_SOURCE", roll: "RISK" }],
  }),
  entry("INFJ", "Styx Prophet", {
    name: "Death Omen",
    type: "ACTIVE",
    description: "Look ahead at the next major penalty public event of this run.",
    tags: ["information", "preview"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "PREVIEW_EVENT", count: 1, detail: "FULL", filter: "NEXT_PENALTY" }],
  }),
  entry("INFP", "Undertow Dreamkeeper", {
    name: "Hold a Grudge",
    type: "PASSIVE",
    description: "The first player to attack you is remembered. If you later help that player, gain 2 Fate.",
    tags: ["fate", "condition", "revenge"],
    trigger: { on: "CONDITION_MET", condition: "HELPED_FIRST_ATTACKER" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
  }),
  entry("ENFJ", "Secret Hierophant", {
    name: "Blood Pact",
    type: "ACTIVE",
    description: "Secretly name an ally. The first time you have helped each other, you each gain 2 Fate.",
    tags: ["bond", "secret", "reward"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "BOND", between: ["SELF", "TARGET"], onMutualHelp: 2, rounds: 12, secret: true }],
  }),
  entry("ENFP", "Night-Prowling Charmer", {
    name: "Trade Secrets",
    type: "ACTIVE",
    description: "Two random players swap one hidden status that can be swapped.",
    tags: ["hidden", "swap", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    effects: [{ kind: "SWAP_STATE", between: ["RANDOM_PLAYER", "RANDOM_PLAYER"], what: "HIDDEN_STATUS" }],
  }),
  entry("ISTJ", "Black-Box Recorder", {
    name: "On Record",
    type: "REACTION",
    description: "When another player's ability hurts you, it still lands, and the same effect hits them too.",
    tags: ["revenge", "copy"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF", fromPlayer: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "COPY_EFFECT", source: "INCOMING", to: "TRIGGER_SOURCE" }],
    copyable: false,
  }),
  entry("ISFJ", "Venom-Tail Guardian", {
    name: "Thorn Guard",
    type: "ACTIVE",
    description: "Protect a player. This round, the first player to attack them loses 1 Fate.",
    tags: ["protect", "punish"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "ADD_STATUS", who: "TARGET", status: "THORN_GUARD", rounds: 1 }],
  }),
  entry("ESTJ", "Underground Magistrate", {
    name: "Reckoning",
    type: "ACTIVE",
    description: "The player who has attacked other players most often this run takes an extra risk roll.",
    tags: ["punish", "roll"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "FORCE_ROLL", who: "TARGET", roll: "RISK" }],
    requires: "TARGET_HAS_MOST_PLAYER_ATTACKS",
  }),
  entry("ESFJ", "Host of the Hidden Feast", {
    name: "Secret Alliance",
    type: "ACTIVE",
    description: "Two random pairs are secretly bonded for 3 rounds. The first time a partner succeeds on a roll, the other gains 1 Fate.",
    tags: ["bond", "secret", "task"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    effects: [{ kind: "BOND", between: ["TARGETS"], pairs: true, onFirstSuccess: 1, rounds: 3, secret: true }],
    count: 4,
  }),
  entry("ISTP", "Shadow-Blade Lurker", {
    name: "Vanish",
    type: "ACTIVE",
    description: "For the rest of this round, other players' active abilities can't target you.",
    tags: ["defence", "immunity"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "IMMUNITY", who: "SELF", scope: "PLAYER_TARGETING", rounds: 1 }],
  }),
  entry("ISFP", "Night Ink Tattooist", {
    name: "Leave a Mark",
    type: "ACTIVE",
    description: "Mark a player. Their next legal reward gives 1 extra Fate.",
    tags: ["reward", "support"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "BONUS_ON_NEXT_REWARD", who: "TARGET", amount: 1 }],
  }),
  entry("ESTP", "Black-Market Raider", {
    name: "Intercept",
    type: "REACTION",
    description: "When another player gains a reward, you gain the same (up to 2 Fate, or the same item).",
    tags: ["reward", "copy"],
    trigger: { on: "PLAYER_GAINS_REWARDS", others: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_REWARD", to: "SELF" }],
    copyable: false,
  }),
  entry("ESFP", "Midnight Phantom", {
    name: "Reversal Party",
    type: "ACTIVE",
    description: "The players with the most and the least Fate swap one temporary status.",
    tags: ["swap", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "SWAP_STATE", between: ["HIGHEST_FATE", "LOWEST_FATE"], what: "TEMP_STATUS" }],
  }),
];
