// ♉ Taurus — stability, hoarding, defence, resources.
import { entry } from "./define.ts";

export const TAURUS = [
  entry("INTJ", "Black-Gold Estate Lord", {
    name: "Long-Term Investment",
    type: "ACTIVE",
    description: "Set something aside: at the start of next round, gain 2 Fate.",
    tags: ["fate", "delay"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "DELAY_EFFECT", rounds: 1, effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }] }],
  }),
  entry("INTP", "Slow-Burn Alchemist", {
    name: "Weigh the Value",
    type: "ACTIVE",
    description: "Look at two random boons and take one of them.",
    tags: ["reward", "choice"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "CHOOSE_ONE", from: "RANDOM_TWO", options: [] }],
  }),
  entry("ENTJ", "Gilded Steward", {
    name: "Requisition",
    type: "ACTIVE",
    description: "Take 1 Fate from each of two players who have some. Nobody can be taken below 0.",
    tags: ["resource", "steal"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "TRANSFER_FATE", from: "TARGETS", to: "SELF", amount: 1 }],
    requires: "TARGETS_HAVE_RESOURCE",
  }),
  entry("ENTP", "Bull-Market Speculator", {
    name: "Double Down",
    type: "ACTIVE",
    description: "Bet on your next roll: on a success, gain 2 extra Fate; on a failure, lose 1 Fate.",
    tags: ["fate", "wager", "roll"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [
      {
        kind: "WAGER",
        onSuccess: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
        onFail: [{ kind: "LOSE_FATE", who: "SELF", amount: 1 }],
      },
    ],
  }),
  entry("INFJ", "Ancient-Root Keeper", {
    name: "Root Shelter",
    type: "ACTIVE",
    description: "You and a chosen player each become immune to the next negative effect.",
    tags: ["defence", "protect"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [
      { kind: "IMMUNITY", who: "SELF", scope: "NEGATIVE", rounds: 1, charges: 1 },
      { kind: "IMMUNITY", who: "TARGET", scope: "NEGATIVE", rounds: 1, charges: 1 },
    ],
  }),
  entry("INFP", "Velvet Collector", {
    name: "Can't Let Go",
    type: "REACTION",
    description: "When one of your buffs is about to end, it lasts one more round.",
    tags: ["buff", "extend"],
    trigger: { on: "STATUS_EXPIRING" },
    target: "SELF",
    effects: [{ kind: "EXTEND_STATUS", who: "SELF", polarity: "POSITIVE", rounds: 1 }],
    requires: "OWN_BUFF_EXPIRING",
  }),
  entry("ENFJ", "Harvest Feast Host", {
    name: "Shared Harvest",
    type: "REACTION",
    description: "When you gain a reward, give 1 Fate to another player and gain 1 extra yourself.",
    tags: ["fate", "support"],
    trigger: { on: "SELF_GAINS_REWARD" },
    target: "OTHER_PLAYER",
    effects: [
      { kind: "TRANSFER_FATE", from: "SELF", to: "TARGET", amount: 1 },
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
    ],
  }),
  entry("ENFP", "Dessert Hoarder", {
    name: "Surprise Stock",
    type: "ACTIVE",
    description: "Gain one random single-use item.",
    tags: ["item"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "GRANT_ITEM", who: "SELF", pool: "CONSUMABLE", count: 1 }],
  }),
  entry("ISTJ", "Stone Vault Keeper", {
    name: "Steady Reserves",
    type: "PASSIVE",
    description: "After two rounds in a row without receiving a negative effect, gain 2 Fate.",
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "NO_NEGATIVE_EFFECT_2_ROUNDS" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
  }),
  entry("ISFJ", "Warm Granary Warden", {
    name: "Emergency Rations",
    type: "PASSIVE",
    description: "When your Fate drops to 0, recover 1 Fate.",
    tags: ["fate", "safety"],
    trigger: { on: "FATE_REACHES_ZERO" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  }),
  entry("ESTJ", "Treasury Overseer", {
    name: "Settlement Day",
    type: "ACTIVE",
    description: "Choose a player. All of their delayed rewards that are already due pay out now.",
    tags: ["reward", "tempo"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "SETTLE_DELAYED", who: "TARGET" }],
  }),
  entry("ESFJ", "Golden Table Steward", {
    name: "Something for Everyone",
    type: "REACTION",
    description: "When you gain a reward, the player with the least Fate gains 1 Fate.",
    tags: ["fate", "support"],
    trigger: { on: "SELF_GAINS_REWARD" },
    target: "LOWEST_FATE",
    effects: [{ kind: "GAIN_FATE", who: "LOWEST_FATE", amount: 1 }],
  }),
  entry("ISTP", "Rockface Mender", {
    name: "Harden",
    type: "ACTIVE",
    description: "Remove one ordinary negative status from yourself or a player in your carriage.",
    tags: ["cleanse", "status"],
    trigger: { on: "OWN_TURN" },
    target: "SAME_CARRIAGE",
    effects: [{ kind: "REMOVE_STATUS", who: "TARGET", polarity: "NEGATIVE", count: 1, ordinaryOnly: true }],
  }),
  entry("ISFP", "Honey Gardener", {
    name: "Slow Growth",
    type: "ACTIVE",
    description: "Gain 1 Fate now, and 1 more at the start of next round.",
    tags: ["fate", "delay"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
      { kind: "DELAY_EFFECT", rounds: 1, effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }] },
    ],
  }),
  entry("ESTP", "Coin Hunter", {
    name: "Quit While Ahead",
    type: "REACTION",
    description: "When another player gains 2 or more Fate at once, you gain 1 Fate.",
    tags: ["fate"],
    trigger: { on: "PLAYER_GAINS_FATE", others: true, minAmount: 2 },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  }),
  entry("ESFP", "King of Plenty", {
    name: "Open the Granary",
    type: "ACTIVE",
    description: "You and two other random players each gain 1 Fate.",
    tags: ["fate", "group"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    effects: [
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
      { kind: "GAIN_FATE", who: "TARGETS", amount: 1 },
    ],
  }),
];
