// ♍ Virgo — correction, analysis, precision, rules.
import { entry } from "./define.ts";

export const VIRGO = [
  entry("INTJ", "Error Eraser", {
    name: "Calibrate",
    type: "REACTION",
    description: "After one of your rolls resolves, raise it to the next higher result tier.",
    tags: ["roll", "modify"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["DISASTER", "FAIL", "SUCCESS"] },
    target: "SELF",
    effects: [{ kind: "MODIFY_RESULT", who: "SELF", tiers: 1, toward: "BETTER" }],
  }),
  entry("INTP", "Loophole Microscope", {
    name: "Debug",
    type: "REACTION",
    description: "When a public event is revealed, cancel it before it takes effect.",
    tags: ["rules", "cancel"],
    trigger: { on: "EVENT_REVEALED" },
    target: "NONE",
    effects: [{ kind: "CANCEL_EFFECT", which: "LAST_SPECIAL_RULE" }],
  }),
  entry("ENTJ", "Process Director", {
    name: "Standardise",
    type: "REACTION",
    description: "When a player fails a roll, have them redo the same kind of roll once.",
    tags: ["roll", "reroll", "support"],
    trigger: { on: "ANY_ROLL_RESOLVED", tiers: ["DISASTER", "FAIL"] },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "REROLL", who: "TRIGGER_SUBJECT", keep: "SECOND" }],
  }),
  entry("ENTP", "Rules Lawyer", {
    name: "Technicality",
    type: "REACTION",
    description: "When another player declares an ability on someone, it has to go to a different legal target instead.",
    tags: ["rules", "redirect"],
    trigger: { on: "TARGETED_ABILITY_DECLARED", others: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "DICTATE_TARGET", who: "TRIGGER_SOURCE", action: "RETARGET_NOW" }],
  }),
  entry("INFJ", "Oracle of Order", {
    name: "Advance Review",
    type: "ACTIVE",
    description: "Look at the next two public events and decide the order they appear in.",
    tags: ["information", "preview", "control"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "PREVIEW_EVENT", count: 2, detail: "FULL", filter: "NEXT_PUBLIC", reorder: true }],
  }),
  entry("INFP", "Collector of Details", {
    name: "Small Joys",
    type: "PASSIVE",
    description: "When two of your rolls in a row are plain Successes, gain 1 Fate.",
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "TWO_PLAIN_SUCCESSES_IN_A_ROW" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  }),
  entry("ENFJ", "Flawless Mentor", {
    name: "Correct Your Form",
    type: "REACTION",
    description: "When a player fails a roll, turn that failure into an ordinary success.",
    tags: ["roll", "support"],
    trigger: { on: "ANY_ROLL_RESOLVED", tiers: ["FAIL"] },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "SET_TIER", who: "TRIGGER_SUBJECT", from: ["FAIL"], to: "SUCCESS" }],
  }),
  entry("ENFP", "Inspired Tinkerer", {
    name: "Close Enough",
    type: "REACTION",
    description: "When you fail a roll, reroll it and keep the better of the two results.",
    tags: ["roll", "reroll"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["DISASTER", "FAIL"] },
    target: "SELF",
    effects: [{ kind: "REROLL", who: "SELF", keep: "BEST" }],
  }),
  entry("ISTJ", "Final Auditor", {
    name: "Recheck",
    type: "ACTIVE",
    description: "Choose a player. Anything waiting for them in a later round (set-aside gains, a prepared shield) arrives now.",
    tags: ["reward", "rules"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "SETTLE_DELAYED", who: "TARGET" }],
  }),
  entry("ISFJ", "Logistics Proofreader", {
    name: "Plan B",
    type: "REACTION",
    description: "When a player's ability legally produces no effect at all, give them back that use.",
    tags: ["ability", "restore", "support"],
    trigger: { on: "SKILL_USED_BY_OTHER", condition: "FIZZLED" },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "RESTORE_SKILL", who: "TRIGGER_SOURCE", onlyIfNoEffect: true }],
  }),
  entry("ESTJ", "Discipline Inspector", {
    name: "Penalty Notice",
    type: "ACTIVE",
    description: "Choose a player whose abilities hurt other players twice this round. They lose 1 Fate.",
    tags: ["fate", "punish"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "LOSE_FATE", who: "TARGET", amount: 1 }],
    requires: "TARGET_ATTACKED_TWICE_THIS_ROUND",
  }),
  entry("ESFJ", "Homeroom Teacher", {
    name: "Make-Up Work",
    type: "ACTIVE",
    description: "The player with the least Fate makes an extra small roll. On a success, they gain 1 Fate.",
    tags: ["fate", "support", "roll"],
    trigger: { on: "OWN_TURN" },
    target: "LOWEST_FATE",
    effects: [
      { kind: "FORCE_ROLL", who: "LOWEST_FATE", roll: "SMALL", onSuccess: [{ kind: "GAIN_FATE", who: "LOWEST_FATE", amount: 1 }] },
    ],
  }),
  entry("ISTP", "Precision Bomb Tech", {
    name: "Defuse",
    type: "ACTIVE",
    description: "Remove one ordinary lasting negative status from any player.",
    tags: ["cleanse", "support"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "REMOVE_STATUS", who: "TARGET", polarity: "NEGATIVE", count: 1, ordinaryOnly: true }],
  }),
  entry("ISFP", "Aesthete of Detail", {
    name: "Fine-Tune",
    type: "REACTION",
    description: "When one of your rolls comes out extreme, move it one tier toward the middle.",
    tags: ["roll", "modify"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["DISASTER", "PERFECT"] },
    target: "SELF",
    effects: [{ kind: "MODIFY_RESULT", who: "SELF", tiers: 1, toward: "MIDDLE" }],
  }),
  entry("ESTP", "Stress Tester", {
    name: "One More Time",
    type: "REACTION",
    description: "When a player succeeds, have them roll again. If they succeed again, you and they each gain 1 Fate.",
    tags: ["roll", "fate", "risk"],
    trigger: { on: "ANY_ROLL_RESOLVED", tiers: ["SUCCESS", "PERFECT"], others: true },
    target: "TRIGGER_SOURCE",
    effects: [
      {
        kind: "FORCE_ROLL",
        who: "TRIGGER_SUBJECT",
        roll: "ORDINARY",
        onSuccess: [
          { kind: "GAIN_FATE", who: "SELF", amount: 1 },
          { kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 1 },
        ],
      },
    ],
  }),
  entry("ESFP", "Perfectionist Actor", {
    name: "Take Two",
    type: "ACTIVE",
    description: "Call a vote. If the majority agrees, the next public event is thrown out and replaced.",
    tags: ["event", "vote"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "VOTE", question: "CONFIRM_REROLL", reward: [{ kind: "REROLL_EVENT", mode: "CONSENSUS" }] }],
  }),
];
