export const STORY_BEATS03 = [
  "LOCKDOWN", "OFFICIAL_FILE", "ARCHIVIST_CONTACT", "FIRST_JUMP",
  "FIRST_REWRITE", "BOOTSTRAP_TRACE", "ROUND2_SIGNAL", "ACT1_CLOSE",
  "ACT2_OPEN", "SURVEILLANCE_FOUND", "ACCESS_LEDGER_FOUND",
  "PROTOTYPE_LOG_FOUND", "ROUND5_ECHO", "INTRUDERS_IDENTIFIED",
  "ACT3_OPEN", "ZERO_DIRECTIVE", "ZERO_CONSULTED", "PREVENTION_ATTEMPT",
  "FOUNDING_PARADOX", "FOUNDER_CLUE", "STAFF_CLUE", "PROTOTYPE_CLUE",
  "JI_NOTE", "HISTORY_CAN_BE_DECEIVED",
  "ACT4_OPEN", "OFFICIAL_HISTORY_END", "NO_TOMORROW_END",
  "DECEIVE_HISTORY_END", "ARCHIVIST_IS_JI", "SEVEN_MINUTES_EARLY",
] as const;

export type StoryBeatId03 = typeof STORY_BEATS03[number];
export type EndingRoute03 = "OFFICIAL_HISTORY" | "NO_TOMORROW" | "DECEIVE_HISTORY";

export const NPCS03 = {
  ARCHIVIST_00: { roomId: "ARCHIVES", year: "Y2026", minAct: 1 },
  ZERO: { roomId: "CENTRAL_HALL", year: "Y2026", minAct: 3 },
} as const;
export type NpcId03 = keyof typeof NPCS03;
