// Core abilities of the BIND family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const BIND: CoreSkill[] = [
  {
    id: "BIND_01",
    category: "BIND",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "bond"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "BOND", between: ["SELF", "TARGET"], onGainFate: 1, rounds: 1 }],
  },
  {
    id: "BIND_02",
    category: "BIND",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["bond", "fate", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    effects: [{ kind: "BOND", between: ["TARGETS"], onFirstSuccess: 1, rounds: 1 }],
  },
  {
    id: "BIND_03",
    category: "BIND",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["bond", "fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "BOND", between: ["TARGET", "SECOND_TARGET"], onMutualHelp: 1, rounds: 1 }],
  },
  {
    id: "BIND_04",
    category: "BIND",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "secret", "bond"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "BOND", between: ["TARGET", "SELF"], onFirstReward: 1, rounds: 12, secret: true, oneWay: true }],
  },
  {
    id: "BIND_05",
    category: "BIND",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["bond", "secret", "reward"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "BOND", between: ["SELF", "TARGET"], onMutualHelp: 2, rounds: 12, secret: true }],
  },
  {
    id: "BIND_06",
    category: "BIND",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["bond", "secret", "task"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    count: 4,
    effects: [{ kind: "BOND", between: ["TARGETS"], pairs: true, onFirstSuccess: 1, rounds: 3, secret: true }],
  },
  {
    id: "BIND_07",
    category: "BIND",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "bond", "group"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    count: 3,
    effects: [{ kind: "BOND", between: ["TARGETS"], onFirstReward: 1, rounds: 1 }],
  },
];
