// Core abilities of the CHALLENGE family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const CHALLENGE: CoreSkill[] = [
  {
    id: "CHALLENGE_01",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "tempo"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "FORCE_ROLL", who: "TARGET", roll: "ORDINARY" }],
  },
  {
    id: "CHALLENGE_02",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "group", "roll"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [
      {
        kind: "GROUP_ROLL",
        who: "ALL",
        mode: "HIGHEST_WINS",
        reward: [{ kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 1 }, { kind: "GAIN_FATE", who: "SELF", amount: 1 }],
      },
    ],
  },
  {
    id: "CHALLENGE_03",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "wager", "roll"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [
      {
        kind: "WAGER",
        onSuccess: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
        onFail: [{ kind: "LOSE_FATE", who: "SELF", amount: 1 }],
      },
    ],
  },
  {
    id: "CHALLENGE_04",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "choice"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "GROUP_ROLL", who: "TARGETS", mode: "PICK_ONE", reward: [] }],
  },
  {
    id: "CHALLENGE_05",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["group", "vote", "reward"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [
      {
        kind: "VOTE",
        question: "MINORITY_REWARD",
        reward: [{ kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 1 }],
      },
    ],
  },
  {
    id: "CHALLENGE_06",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["challenge", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "CHALLENGE", against: "TARGET", winnerGains: 2, scope: "SELF_VS_TARGET" }],
  },
  {
    id: "CHALLENGE_07",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["challenge", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "CHALLENGE", against: "TARGET", winnerGains: 2, scope: "SELF_VS_TARGET" }],
  },
  {
    id: "CHALLENGE_08",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["vote", "fate", "group"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [
      {
        kind: "VOTE",
        question: "PICK_PLAYER",
        reward: [{ kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 2 }, { kind: "GAIN_FATE", who: "SELF", amount: 2 }],
      },
    ],
  },
  {
    id: "CHALLENGE_09",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "support", "roll"],
    trigger: { on: "OWN_TURN" },
    target: "LOWEST_FATE",
    effects: [
      {
        kind: "FORCE_ROLL",
        who: "LOWEST_FATE",
        roll: "SMALL",
        onSuccess: [{ kind: "GAIN_FATE", who: "LOWEST_FATE", amount: 1 }],
      },
    ],
  },
  {
    id: "CHALLENGE_10",
    category: "CHALLENGE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "fate", "risk"],
    trigger: { on: "ANY_ROLL_RESOLVED", tiers: ["SUCCESS", "PERFECT"], others: true },
    target: "TRIGGER_SOURCE",
    effects: [
      {
        kind: "FORCE_ROLL",
        who: "TRIGGER_SUBJECT",
        roll: "ORDINARY",
        onSuccess: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }, { kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 1 }],
      },
    ],
  },
  {
    id: "CHALLENGE_11",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["event", "vote"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "VOTE", question: "CONFIRM_REROLL", reward: [{ kind: "REROLL_EVENT", mode: "CONSENSUS" }] }],
  },
  {
    id: "CHALLENGE_12",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["contest", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "CHALLENGE", against: "SECOND_TARGET", winnerGains: 2, tieGains: 1, scope: "TWO_TARGETS" }],
  },
  {
    id: "CHALLENGE_13",
    category: "CHALLENGE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["event", "vote"],
    trigger: { on: "CHOICE_EVENT_REVEALED" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "VOTE", question: "PICK_OUTCOME" }],
  },
  {
    id: "CHALLENGE_14",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["punish", "roll"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    requires: "TARGET_HAS_MOST_PLAYER_ATTACKS",
    effects: [{ kind: "FORCE_ROLL", who: "TARGET", roll: "RISK" }],
  },
  {
    id: "CHALLENGE_15",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "risk", "wager"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [
      {
        kind: "WAGER",
        onSuccess: [{ kind: "GAIN_FATE", who: "SELF", amount: 3 }],
        onFail: [{ kind: "LOSE_FATE", who: "SELF", amount: 1 }],
      },
    ],
  },
  {
    id: "CHALLENGE_16",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["group", "roll", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "UP_TO_THREE_PLAYERS",
    effects: [
      {
        kind: "GROUP_ROLL",
        who: "TARGETS",
        mode: "SUM_THRESHOLD",
        reward: [{ kind: "GAIN_FATE", who: "TARGETS", amount: 1 }],
      },
    ],
  },
  {
    id: "CHALLENGE_17",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "fate", "tempo"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [
      {
        kind: "FORCE_ROLL",
        who: "TARGETS",
        roll: "ORDINARY",
        onSuccess: [{ kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 1 }],
      },
    ],
  },
  {
    id: "CHALLENGE_18",
    category: "CHALLENGE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["challenge", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "HIGHEST_FATE",
    effects: [{ kind: "CHALLENGE", against: "TARGET", winnerGains: 2, scope: "SELF_VS_TARGET" }],
  },
];
