// Core abilities of the CONTROL_EVENT family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const CONTROL_EVENT: CoreSkill[] = [
  {
    id: "CONTROL_EVENT_01",
    category: "CONTROL_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["event", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "RANDOM_EVENT", size: "SMALL", participants: "SELF" }],
  },
  {
    id: "CONTROL_EVENT_02",
    category: "CONTROL_EVENT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["choice", "deceit"],
    trigger: { on: "OWN_CHOICE_MADE" },
    target: "SELF",
    effects: [{ kind: "REVISE_CHOICE" }],
  },
  {
    id: "CONTROL_EVENT_03",
    category: "CONTROL_EVENT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["information", "event"],
    trigger: { on: "CHOICE_EVENT_REVEALED" },
    target: "SELF",
    effects: [{ kind: "MODIFY_EVENT", change: "DECIDER_SELF" }],
  },
  {
    id: "CONTROL_EVENT_04",
    category: "CONTROL_EVENT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["event", "reroll"],
    trigger: { on: "EVENT_REVEALED" },
    target: "NONE",
    effects: [{ kind: "REROLL_EVENT", mode: "SAME_CATEGORY" }],
  },
  {
    id: "CONTROL_EVENT_05",
    category: "CONTROL_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["event"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "MODIFY_EVENT", change: "NEXT_DECIDER" }],
  },
  {
    id: "CONTROL_EVENT_06",
    category: "CONTROL_EVENT",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["event", "reward"],
    trigger: { on: "CONDITION_MET", condition: "SUCCEEDED_TWO_ROUNDS_RUNNING" },
    target: "SELF",
    effects: [{ kind: "RANDOM_EVENT", size: "REWARD", participants: "SELF" }],
  },
  {
    id: "CONTROL_EVENT_07",
    category: "CONTROL_EVENT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["event", "fate", "escape"],
    trigger: { on: "EVENT_REVEALED" },
    target: "SELF",
    effects: [{ kind: "SKIP_EVENT", who: "SELF" }, { kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
  {
    id: "CONTROL_EVENT_08",
    category: "CONTROL_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["event", "choice"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "RANDOM_EVENT", size: "STANDARD", choices: 3, pick: "CHOOSE", participants: "SELF" }],
  },
  {
    id: "CONTROL_EVENT_09",
    category: "CONTROL_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["event", "group"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "RANDOM_EVENT", size: "MULTI", participants: "TARGETS" }],
  },
  {
    id: "CONTROL_EVENT_10",
    category: "CONTROL_EVENT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["event", "escape"],
    trigger: { on: "EVENT_REVEALED" },
    target: "SELF",
    effects: [{ kind: "SKIP_EVENT", who: "SELF", reroute: true }],
  },
  {
    id: "CONTROL_EVENT_11",
    category: "CONTROL_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["event", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "RANDOM_EVENT", size: "MINIGAME", participants: "SELF" }],
  },
  {
    id: "CONTROL_EVENT_12",
    category: "CONTROL_EVENT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["event", "control"],
    trigger: { on: "EVENT_REVEALED" },
    target: "NONE",
    effects: [{ kind: "REROLL_EVENT", mode: "OTHER_CATEGORY" }],
  },
  {
    id: "CONTROL_EVENT_13",
    category: "CONTROL_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["event", "group", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "RANDOM_EVENT", size: "SMALL", participants: "ALL", split: "TWO_GROUPS" }],
  },
  {
    id: "CONTROL_EVENT_14",
    category: "CONTROL_EVENT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["event", "rules"],
    trigger: { on: "EVENT_REVEALED" },
    target: "NONE",
    effects: [{ kind: "MODIFY_EVENT", change: "REMOVE_CONDITION" }],
  },
  {
    id: "CONTROL_EVENT_15",
    category: "CONTROL_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["event", "planning"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "MODIFY_EVENT", change: "BIAS_CHOSEN" }],
  },
  {
    id: "CONTROL_EVENT_16",
    category: "CONTROL_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["event", "group"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "RANDOM_EVENT", size: "STANDARD", participants: "TARGETS" }],
  },
  {
    id: "CONTROL_EVENT_17",
    category: "CONTROL_EVENT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["event", "chaos"],
    trigger: { on: "EVENT_REVEALED" },
    target: "NONE",
    effects: [{ kind: "MODIFY_EVENT", change: "RANDOM_ASPECT" }],
  },
  {
    id: "CONTROL_EVENT_18",
    category: "CONTROL_EVENT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["event", "evade"],
    trigger: { on: "EVENT_REVEALED" },
    target: "SELF",
    effects: [{ kind: "SKIP_EVENT", who: "SELF", hideUntil: "NEXT_ROUND" }],
  },
  {
    id: "CONTROL_EVENT_19",
    category: "CONTROL_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["event", "risk"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "RANDOM_EVENT", size: "STANDARD", choices: 2, pick: "HIGHER_REWARD", participants: "SELF" }],
  },
];
