// Core abilities of the COPY_EFFECT family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const COPY_EFFECT: CoreSkill[] = [
  {
    id: "COPY_EFFECT_01",
    category: "COPY_EFFECT",
    type: "REACTION",
    maxUses: 1,
    copyable: false,
    tags: ["copy"],
    trigger: { on: "SKILL_USED_BY_OTHER" },
    target: "SELF",
    effects: [{ kind: "COPY_EFFECT", source: "LAST_SKILL", to: "SELF" }],
  },
  {
    id: "COPY_EFFECT_02",
    category: "COPY_EFFECT",
    type: "REACTION",
    maxUses: 1,
    copyable: false,
    tags: ["buff", "copy", "support"],
    trigger: { on: "PLAYER_GAINS_BUFF" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_BUFF", to: "TARGET", weaken: true }],
  },
  {
    id: "COPY_EFFECT_03",
    category: "COPY_EFFECT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: false,
    tags: ["buff", "copy"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_BUFF", to: "SELF", rounds: 1 }],
  },
  {
    id: "COPY_EFFECT_04",
    category: "COPY_EFFECT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["reward", "balance"],
    trigger: { on: "PLAYER_GAINS_REWARDS" },
    target: "NONE",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_REWARD", to: "LOWEST_FATE" }],
  },
  {
    id: "COPY_EFFECT_05",
    category: "COPY_EFFECT",
    type: "REACTION",
    maxUses: 1,
    copyable: false,
    tags: ["reward", "copy"],
    trigger: { on: "PLAYER_GAINS_REWARDS", others: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_REWARD", to: "SELF" }],
  },
  {
    id: "COPY_EFFECT_06",
    category: "COPY_EFFECT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["event", "support", "reward"],
    trigger: { on: "SELF_GAINS_REWARD" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_REWARD", to: "TARGET" }],
  },
  {
    id: "COPY_EFFECT_07",
    category: "COPY_EFFECT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: false,
    tags: ["copy", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "COPY_EFFECT", source: "RANDOM_OTHER_ZODIAC" }],
  },
  {
    id: "COPY_EFFECT_08",
    category: "COPY_EFFECT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: false,
    tags: ["copy", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "COPY_EFFECT", source: "RANDOM_ROSTER" }],
  },
  {
    id: "COPY_EFFECT_09",
    category: "COPY_EFFECT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["copy", "buff"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_ZODIAC_BUFF", to: "SELF", rounds: 1 }],
  },
  {
    id: "COPY_EFFECT_10",
    category: "COPY_EFFECT",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["support", "copy", "buff"],
    trigger: { on: "PLAYER_GAINS_BUFF" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "COPY_EFFECT", source: "TARGET_BUFF", to: "TARGET", weaken: true }],
  },
];
