// Core abilities of the EMPOWER family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const EMPOWER: CoreSkill[] = [
  {
    id: "EMPOWER_01",
    category: "EMPOWER",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["buff", "extend"],
    trigger: { on: "STATUS_EXPIRING" },
    target: "SELF",
    requires: "OWN_BUFF_EXPIRING",
    effects: [{ kind: "EXTEND_STATUS", who: "SELF", polarity: "POSITIVE", rounds: 1 }],
  },
  {
    id: "EMPOWER_02",
    category: "EMPOWER",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "support"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "ADD_STATUS", who: "TARGET", status: "REROLL_NEXT_FAILURE", rounds: 3 }],
  },
  {
    id: "EMPOWER_03",
    category: "EMPOWER",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "taunt", "shield"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [
      { kind: "ADD_STATUS", who: "SELF", status: "TAUNT", rounds: 1 },
      { kind: "SHIELD", who: "SELF", charges: 1 },
    ],
  },
  {
    id: "EMPOWER_04",
    category: "EMPOWER",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["protect", "punish"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "ADD_STATUS", who: "TARGET", status: "THORN_GUARD", rounds: 1 }],
  },
  {
    id: "EMPOWER_05",
    category: "EMPOWER",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["support", "status"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "ADD_STATUS", who: "TARGET", status: "MINOR_BUFF", rounds: 2, random: true }],
  },
  {
    id: "EMPOWER_07",
    category: "EMPOWER",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["status", "group", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "ADD_STATUS", who: "ALL", status: "DREAM", rounds: 1, random: true }],
  },
];
