// Core abilities of the GAIN_RESOURCE family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const GAIN_RESOURCE: CoreSkill[] = [
  {
    id: "GAIN_RESOURCE_01",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }, { kind: "GAIN_FATE", who: "TARGET", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_02",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "FIRST_SUCCESS_THIS_ROUND" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_03",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "GAIN_FATE", who: "TARGETS", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_04",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["choice", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "CHOOSE_ONE", from: "RANDOM_TWO", options: [] }],
  },
  {
    id: "GAIN_RESOURCE_05",
    category: "GAIN_RESOURCE",
    type: "REACTION",
    maxUses: 1,
    copyable: false,
    tags: ["tempo", "interrupt"],
    trigger: { on: "SKILL_USED_BY_OTHER" },
    target: "SELF",
    effects: [{ kind: "GAIN_AP", who: "SELF", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_06",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "delay"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "DELAY_EFFECT", rounds: 1, effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }] }],
  },
  {
    id: "GAIN_RESOURCE_07",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["reward", "choice"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "CHOOSE_ONE", from: "RANDOM_TWO", options: [] }],
  },
  {
    id: "GAIN_RESOURCE_08",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["resource", "steal"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    requires: "TARGETS_HAVE_RESOURCE",
    effects: [{ kind: "TRANSFER_FATE", from: "TARGETS", to: "SELF", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_09",
    category: "GAIN_RESOURCE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "support"],
    trigger: { on: "SELF_GAINS_REWARD" },
    target: "OTHER_PLAYER",
    effects: [
      { kind: "TRANSFER_FATE", from: "SELF", to: "TARGET", amount: 1 },
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
    ],
  },
  {
    id: "GAIN_RESOURCE_10",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["item"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "GRANT_ITEM", who: "SELF", pool: "CONSUMABLE", count: 1 }],
  },
  {
    id: "GAIN_RESOURCE_11",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "NO_NEGATIVE_EFFECT_2_ROUNDS" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
  },
  {
    id: "GAIN_RESOURCE_12",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "safety"],
    trigger: { on: "FATE_REACHES_ZERO" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_13",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["reward", "tempo"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "SETTLE_DELAYED", who: "TARGET" }],
  },
  {
    id: "GAIN_RESOURCE_14",
    category: "GAIN_RESOURCE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "support"],
    trigger: { on: "SELF_GAINS_REWARD" },
    target: "LOWEST_FATE",
    effects: [{ kind: "GAIN_FATE", who: "LOWEST_FATE", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_15",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "delay"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
      { kind: "DELAY_EFFECT", rounds: 1, effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }] },
    ],
  },
  {
    id: "GAIN_RESOURCE_16",
    category: "GAIN_RESOURCE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["fate"],
    trigger: { on: "PLAYER_GAINS_FATE", others: true, minAmount: 2 },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_17",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "group"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }, { kind: "GAIN_FATE", who: "TARGETS", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_18",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "LOWEST_FATE",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }, { kind: "GAIN_FATE", who: "LOWEST_FATE", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_19",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["reward", "group"],
    trigger: { on: "OWN_TURN" },
    target: "UP_TO_THREE_PLAYERS",
    effects: [{ kind: "BONUS_ON_NEXT_REWARD", who: "TARGETS", amount: 1, scope: "FIRST_THIS_ROUND" }],
  },
  {
    id: "GAIN_RESOURCE_20",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "NO_ATTACK_2_ROUNDS" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
  },
  {
    id: "GAIN_RESOURCE_21",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "LOWEST_FATE",
    effects: [{ kind: "GAIN_FATE", who: "TWO_LOWEST_FATE", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_22",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "help"],
    trigger: { on: "HELPED_BY_PLAYER" },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }, { kind: "GAIN_FATE", who: "TRIGGER_SOURCE", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_23",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["reward", "group"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    count: 3,
    effects: [{ kind: "BONUS_ON_NEXT_REWARD", who: "TARGETS", amount: 1, scope: "FIRST_THIS_ROUND" }],
  },
  {
    id: "GAIN_RESOURCE_24",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition"],
    trigger: { on: "ROUND_END" },
    target: "SELF",
    requires: "NOT_TARGETED_THIS_ROUND",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
  },
  {
    id: "GAIN_RESOURCE_25",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["reward", "support"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "DOUBLE_REWARD", who: "TARGET", next: "SUCCESS_REWARD" }],
  },
  {
    id: "GAIN_RESOURCE_26",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "SOLE_GAINER_OF_PUBLIC_EVENT" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_27",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "THIRD_SUCCESS_THIS_RUN" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 3 }],
  },
  {
    id: "GAIN_RESOURCE_28",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "support"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [
      { kind: "GAIN_FATE", who: "TARGET", amount: 1 },
      {
        kind: "CONDITIONAL",
        condition: "TARGET_HELPED_BY_ANOTHER_THIS_ROUND",
        then: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
      },
    ],
  },
  {
    id: "GAIN_RESOURCE_29",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "TWO_PLAIN_SUCCESSES_IN_A_ROW" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_30",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["reward", "rules"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "SETTLE_DELAYED", who: "TARGET" }],
  },
  {
    id: "GAIN_RESOURCE_31",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "balance"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "TRANSFER_FATE", from: "HIGHEST_FATE", to: "LOWEST_FATE", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_32",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition", "revenge"],
    trigger: { on: "CONDITION_MET", condition: "HELPED_FIRST_ATTACKER" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
  },
  {
    id: "GAIN_RESOURCE_33",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["reward", "support"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "BONUS_ON_NEXT_REWARD", who: "TARGET", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_34",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition", "counter"],
    trigger: { on: "CONDITION_MET", condition: "THREE_ROLL_KINDS" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
  },
  {
    id: "GAIN_RESOURCE_35",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["item", "support"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "GRANT_ITEM", who: "TARGET", pool: "BUFF", count: 1 }],
  },
  {
    id: "GAIN_RESOURCE_36",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "roll", "condition"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["DISASTER", "PERFECT"] },
    target: "SELF",
    requires: "RAW_ROLL_1_OR_6",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_37",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["reward", "risk"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "DOUBLE_REWARD", who: "SELF", next: "REWARD", penaltyToo: true }],
  },
  {
    id: "GAIN_RESOURCE_38",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition", "patience"],
    trigger: { on: "CONDITION_MET", condition: "NO_ACTIVE_ABILITY_2_ROUNDS" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 2 }],
  },
  {
    id: "GAIN_RESOURCE_39",
    category: "GAIN_RESOURCE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "support"],
    trigger: { on: "ANY_ROLL_RESOLVED", tiers: ["SUCCESS", "PERFECT"] },
    target: "LOWEST_FATE",
    requires: "SUBJECT_HAS_LOWEST_FATE",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }, { kind: "GAIN_FATE", who: "TRIGGER_SUBJECT", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_40",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition"],
    trigger: { on: "CONDITION_MET", condition: "TWO_CONSECUTIVE_SUCCESSES" },
    target: "SELF",
    effects: [{ kind: "BONUS_ON_NEXT_REWARD", who: "SELF", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_41",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "condition", "group"],
    trigger: { on: "CONDITION_MET", condition: "THREE_PLAYERS_SUCCEEDED_THIS_ROUND" },
    target: "SELF",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_42",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "status"],
    trigger: { on: "STATUS_EXPIRING", others: false },
    target: "SELF",
    requires: "EXPIRING_STATUS_IS_OWN_BUFF",
    effects: [{ kind: "CONVERT_STATUS", who: "SELF", into: "FATE", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_43",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "group"],
    trigger: { on: "ROUND_END" },
    target: "SELF",
    requires: "SOMEONE_SUCCEEDED_THIS_ROUND",
    effects: [{ kind: "GAIN_FATE", who: "LAST_SUCCESS", amount: 1 }, { kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
  {
    id: "GAIN_RESOURCE_44",
    category: "GAIN_RESOURCE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["rules", "group"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [
      {
        kind: "DELAY_EFFECT",
        rounds: 1,
        effects: [{ kind: "MODIFY_RULE", rule: "RANDOM_GLOBAL_MODIFIER", delta: 1, rounds: 1 }],
      },
    ],
  },
  {
    id: "GAIN_RESOURCE_45",
    category: "GAIN_RESOURCE",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "support"],
    trigger: { on: "PLAYER_GAINS_REWARDS", others: true },
    target: "LOWEST_FATE",
    requires: "SUBJECT_HAS_LOWEST_FATE",
    effects: [{ kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
];
