// Core abilities of the PREVIEW_EVENT family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const PREVIEW_EVENT: CoreSkill[] = [
  {
    id: "PREVIEW_EVENT_01",
    category: "PREVIEW_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["information", "preview"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "PREVIEW_EVENT", count: 1, detail: "TYPE", filter: "NEXT_PUBLIC" }],
  },
  {
    id: "PREVIEW_EVENT_02",
    category: "PREVIEW_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["information", "hidden"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "REVEAL_HIDDEN", who: "TARGET", what: "STATUS" }],
  },
  {
    id: "PREVIEW_EVENT_03",
    category: "PREVIEW_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["information", "preview"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "PREVIEW_EVENT", count: 1, detail: "BIAS", filter: "NEXT_PUBLIC" }],
  },
  {
    id: "PREVIEW_EVENT_04",
    category: "PREVIEW_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["information", "preview", "control"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "PREVIEW_EVENT", count: 2, detail: "FULL", filter: "NEXT_PUBLIC", reorder: true }],
  },
  {
    id: "PREVIEW_EVENT_05",
    category: "PREVIEW_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["information", "hidden"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "REVEAL_HIDDEN", who: "SELF", what: "EVENT_EFFECT" }],
  },
  {
    id: "PREVIEW_EVENT_06",
    category: "PREVIEW_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["information", "preview"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "PREVIEW_EVENT", count: 1, detail: "FULL", filter: "NEXT_PENALTY" }],
  },
  {
    id: "PREVIEW_EVENT_07",
    category: "PREVIEW_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["information", "preview"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "PREVIEW_EVENT", count: 3, detail: "TYPE", filter: "NEXT_PUBLIC" }],
  },
  {
    id: "PREVIEW_EVENT_08",
    category: "PREVIEW_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["information", "hidden"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "REVEAL_HIDDEN", who: "SELF", what: "EVENT_EFFECT", mayVeto: true }],
  },
  {
    id: "PREVIEW_EVENT_09",
    category: "PREVIEW_EVENT",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["information", "preview"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "PREVIEW_EVENT", count: 1, detail: "FULL", filter: "TARGETING_SELF" }],
  },
];
