// Core abilities of the REMOVE_STATUS family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const REMOVE_STATUS: CoreSkill[] = [
  {
    id: "REMOVE_STATUS_01",
    category: "REMOVE_STATUS",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["cleanse", "status"],
    trigger: { on: "OWN_TURN" },
    target: "SAME_CARRIAGE",
    effects: [{ kind: "REMOVE_STATUS", who: "TARGET", polarity: "NEGATIVE", count: 1, ordinaryOnly: true }],
  },
  {
    id: "REMOVE_STATUS_02",
    category: "REMOVE_STATUS",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["cleanse", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    effects: [{ kind: "REMOVE_STATUS", who: "RANDOM_PLAYER", polarity: "NEGATIVE", count: 1, ordinaryOnly: true }],
  },
  {
    id: "REMOVE_STATUS_03",
    category: "REMOVE_STATUS",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["cleanse", "support"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "REMOVE_STATUS", who: "TARGET", polarity: "NEGATIVE", count: 1, ordinaryOnly: true }],
  },
  {
    id: "REMOVE_STATUS_04",
    category: "REMOVE_STATUS",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["status", "cleanse", "group"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "REMOVE_STATUS", who: "ALL", polarity: "ANY", count: "ALL" }],
  },
  {
    id: "REMOVE_STATUS_05",
    category: "REMOVE_STATUS",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["support", "cleanse"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "REMOVE_STATUS", who: "TARGET", polarity: "NEGATIVE", count: 1, ordinaryOnly: true }],
  },
];
