// Core abilities of the REROLL family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const REROLL: CoreSkill[] = [
  {
    id: "REROLL_01",
    category: "REROLL",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "reroll"],
    trigger: { on: "OWN_ROLL_RESOLVED" },
    target: "SELF",
    effects: [{ kind: "REROLL", who: "SELF", keep: "SECOND" }],
  },
  {
    id: "REROLL_02",
    category: "REROLL",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "reroll", "support"],
    trigger: { on: "ANY_ROLL_RESOLVED", tiers: ["DISASTER", "FAIL"], others: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "REROLL", who: "TRIGGER_SUBJECT", keep: "SECOND" }],
  },
  {
    id: "REROLL_03",
    category: "REROLL",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "reroll", "support"],
    trigger: { on: "ANY_ROLL_RESOLVED", tiers: ["DISASTER", "FAIL"] },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "REROLL", who: "TRIGGER_SUBJECT", keep: "SECOND" }],
  },
  {
    id: "REROLL_04",
    category: "REROLL",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "reroll"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["DISASTER", "FAIL"] },
    target: "SELF",
    effects: [{ kind: "REROLL", who: "SELF", keep: "BEST" }],
  },
  {
    id: "REROLL_05",
    category: "REROLL",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "reroll"],
    trigger: { on: "OWN_ROLL_RESOLVED" },
    target: "SELF",
    effects: [{ kind: "REROLL", who: "SELF", keep: "AVERAGE" }],
  },
  {
    id: "REROLL_06",
    category: "REROLL",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "reroll", "group"],
    trigger: { on: "PUBLIC_ROLL_DONE" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "REROLL", who: "ALL", keep: "SECOND", scope: "ALL" }],
  },
  {
    id: "REROLL_07",
    category: "REROLL",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "reroll"],
    trigger: { on: "OWN_ROLL_RESOLVED" },
    target: "SELF",
    effects: [{ kind: "REROLL", who: "SELF", keep: "CHOOSE" }],
  },
  {
    id: "REROLL_08",
    category: "REROLL",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "reroll", "disrupt"],
    trigger: { on: "ANY_ROLL_RESOLVED", others: true },
    target: "ANY_PLAYER",
    effects: [{ kind: "REROLL", who: "TRIGGER_SUBJECT", keep: "SECOND" }],
  },
];
