// Core abilities of the RETALIATE family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const RETALIATE: CoreSkill[] = [
  {
    id: "RETALIATE_01",
    category: "RETALIATE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["counter", "status"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF", fromPlayer: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "COPY_EFFECT", source: "INCOMING", to: "TRIGGER_SOURCE", weaken: true }],
  },
  {
    id: "RETALIATE_02",
    category: "RETALIATE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "convert"],
    trigger: { on: "ATTACKED_BY_PLAYER" },
    target: "TRIGGER_SOURCE",
    effects: [
      { kind: "CANCEL_EFFECT", which: "INCOMING" },
      { kind: "GAIN_FATE", who: "SELF", amount: 1 },
      { kind: "GAIN_FATE", who: "TRIGGER_SOURCE", amount: 1 },
    ],
  },
  {
    id: "RETALIATE_03",
    category: "RETALIATE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "cancel", "fate"],
    trigger: { on: "FATE_THEFT_ATTEMPTED" },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "CANCEL_EFFECT", which: "FATE_THEFT" }],
  },
  {
    id: "RETALIATE_04",
    category: "RETALIATE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["revenge", "roll"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF", fromPlayer: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "FORCE_ROLL", who: "TRIGGER_SOURCE", roll: "RISK" }],
  },
  {
    id: "RETALIATE_05",
    category: "RETALIATE",
    type: "REACTION",
    maxUses: 1,
    copyable: false,
    tags: ["revenge", "copy"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF", fromPlayer: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "COPY_EFFECT", source: "INCOMING", to: "TRIGGER_SOURCE" }],
  },
];
