// Core abilities of the SHIELD family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const SHIELD: CoreSkill[] = [
  {
    id: "SHIELD_01",
    category: "SHIELD",
    type: "PASSIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "reduce"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF" },
    target: "SELF",
    effects: [{ kind: "REDUCE_EFFECT", levels: 1 }],
  },
  {
    id: "SHIELD_02",
    category: "SHIELD",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "cancel"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF" },
    target: "SELF",
    effects: [{ kind: "CANCEL_EFFECT", which: "INCOMING" }],
  },
  {
    id: "SHIELD_03",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "protect"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [
      { kind: "IMMUNITY", who: "SELF", scope: "NEGATIVE", rounds: 1, charges: 1 },
      { kind: "IMMUNITY", who: "TARGET", scope: "NEGATIVE", rounds: 1, charges: 1 },
    ],
  },
  {
    id: "SHIELD_04",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "protect"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "IMMUNITY", who: "TARGET", scope: "PLAYER_TARGETING", rounds: 1 }],
  },
  {
    id: "SHIELD_05",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [
      { kind: "IMMUNITY", who: "SELF", scope: "NEGATIVE", rounds: 1, charges: 99 },
      { kind: "GAIN_AP", who: "SELF", amount: -3 },
    ],
  },
  {
    id: "SHIELD_06",
    category: "SHIELD",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "protect", "fate"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_ANY", others: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "CANCEL_EFFECT", which: "INCOMING" }, { kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
  {
    id: "SHIELD_07",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "shield"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "SHIELD", who: "TARGET", charges: 1 }],
  },
  {
    id: "SHIELD_08",
    category: "SHIELD",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["cancel"],
    trigger: { on: "TARGETED_ABILITY_DECLARED" },
    target: "NONE",
    requires: "PENDING_ABILITY_MOVES_RESOURCES",
    effects: [{ kind: "CANCEL_EFFECT", which: "PENDING_TRANSFER" }],
  },
  {
    id: "SHIELD_09",
    category: "SHIELD",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "protect", "fate"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_ANY", others: true },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "CANCEL_EFFECT", which: "INCOMING" }, { kind: "GAIN_FATE", who: "SELF", amount: 1 }],
  },
  {
    id: "SHIELD_10",
    category: "SHIELD",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["rules", "cancel"],
    trigger: { on: "EVENT_REVEALED" },
    target: "NONE",
    effects: [{ kind: "CANCEL_EFFECT", which: "LAST_SPECIAL_RULE" }],
  },
  {
    id: "SHIELD_11",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["cancel", "relationship"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "CANCEL_EFFECT", which: "OPPOSITION_STATE" }],
  },
  {
    id: "SHIELD_12",
    category: "SHIELD",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["rules", "cancel"],
    trigger: { on: "TARGETED_ABILITY_DECLARED" },
    target: "NONE",
    requires: "PENDING_ABILITY_TAKES",
    effects: [{ kind: "CANCEL_EFFECT", which: "CONFLICTING_ABILITIES" }],
  },
  {
    id: "SHIELD_13",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["control", "defence"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "FORBID_TARGETING", who: "TARGET", protects: "SELF", uses: 1 }],
  },
  {
    id: "SHIELD_14",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "immunity"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "IMMUNITY", who: "SELF", scope: "PLAYER_TARGETING", rounds: 1 }],
  },
  {
    id: "SHIELD_15",
    category: "SHIELD",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["event", "escape", "defence"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["DISASTER", "FAIL"] },
    target: "SELF",
    effects: [{ kind: "NEGATE_PENALTY", who: "SELF", also: "EXIT_EVENT" }],
  },
  {
    id: "SHIELD_16",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "shield"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "SHIELD", who: "SELF", charges: 1, fromRound: "NEXT" }],
  },
  {
    id: "SHIELD_17",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "support"],
    trigger: { on: "OWN_TURN" },
    target: "ANY_PLAYER",
    effects: [{ kind: "NEGATE_PENALTY", who: "TARGET", also: "KEEP_RESOURCES" }],
  },
  {
    id: "SHIELD_18",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "fate"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "LOCK_FATE", who: "SELF", rounds: 1 }],
  },
  {
    id: "SHIELD_19",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "immunity"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "IMMUNITY", who: "SELF", scope: "GROUP_NEGATIVE", rounds: 99, charges: 1 }],
  },
  {
    id: "SHIELD_20",
    category: "SHIELD",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "cancel"],
    trigger: { on: "TARGETED_ABILITY_DECLARED" },
    target: "SELF",
    requires: "ABILITY_TARGETS_SELF",
    effects: [{ kind: "CANCEL_EFFECT", which: "INCOMING" }],
  },
  {
    id: "SHIELD_21",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "immunity"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "IMMUNITY", who: "SELF", scope: "PLAYER_INTERACTION", rounds: 1 }],
  },
  {
    id: "EMPOWER_06",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "deception"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "SHIELD", who: "SELF", charges: 1 }],
  },
  {
    id: "SHIELD_22",
    category: "SHIELD",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "delay"],
    trigger: { on: "OWN_ROLL_RESOLVED", tiers: ["FAIL", "DISASTER"] },
    target: "SELF",
    effects: [
      { kind: "NEGATE_PENALTY", who: "SELF" },
      { kind: "DELAY_EFFECT", rounds: 1, effects: [{ kind: "GAIN_AP", who: "SELF", amount: 1 }] },
    ],
  },
  {
    id: "SHIELD_23",
    category: "SHIELD",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["cancel", "group"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "CANCEL_EFFECT", which: "GLOBAL_EFFECT" }],
  },
];
