// Core abilities of the SWAP_STATE family. Mechanics only: no names, no scenario objects.
import type { CoreSkill } from "./types.ts";

export const SWAP_STATE: CoreSkill[] = [
  {
    id: "SWAP_STATE_01",
    category: "SWAP_STATE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["swap", "status"],
    trigger: { on: "OWN_TURN" },
    target: "OTHER_PLAYER",
    effects: [{ kind: "SWAP_STATE", between: ["SELF", "TARGET"], what: "TEMP_STATUS" }],
  },
  {
    id: "SWAP_STATE_02",
    category: "SWAP_STATE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["bond", "swap"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "SWAP_STATE", between: ["TARGET", "SECOND_TARGET"], what: "BOND" }],
  },
  {
    id: "SWAP_STATE_03",
    category: "SWAP_STATE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["roll", "swap"],
    trigger: { on: "ANY_ROLL_RESOLVED" },
    target: "TRIGGER_SOURCE",
    effects: [{ kind: "SWAP_STATE", between: ["TRIGGER_SUBJECT", "SELF"], what: "ROLL_RESULT" }],
  },
  {
    id: "SWAP_STATE_04",
    category: "SWAP_STATE",
    type: "REACTION",
    maxUses: 1,
    copyable: true,
    tags: ["defence", "status", "swap"],
    trigger: { on: "NEGATIVE_EFFECT_TARGETS_SELF" },
    target: "SELF",
    requires: "HAS_OTHER_TEMP_STATUS",
    effects: [{ kind: "SWAP_STATE", between: ["SELF", "SELF"], what: "STATUS_FOR_STATUS" }],
  },
  {
    id: "SWAP_STATE_05",
    category: "SWAP_STATE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "balance"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "BALANCE_FATE", between: ["TARGET", "SECOND_TARGET"], maxStep: 2 }],
  },
  {
    id: "SWAP_STATE_06",
    category: "SWAP_STATE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["bond", "swap"],
    trigger: { on: "OWN_TURN" },
    target: "TWO_PLAYERS",
    effects: [{ kind: "SWAP_STATE", between: ["TARGET", "SECOND_TARGET"], what: "BOND" }],
  },
  {
    id: "SWAP_STATE_07",
    category: "SWAP_STATE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["fate", "balance"],
    trigger: { on: "OWN_TURN" },
    target: "NONE",
    effects: [{ kind: "BALANCE_FATE", between: ["HIGHEST_FATE", "LOWEST_FATE"], maxStep: 1 }],
  },
  {
    id: "SWAP_STATE_08",
    category: "SWAP_STATE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["hidden", "swap", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "RANDOM_PLAYERS",
    effects: [{ kind: "SWAP_STATE", between: ["RANDOM_PLAYER", "RANDOM_PLAYER"], what: "HIDDEN_STATUS" }],
  },
  {
    id: "SWAP_STATE_09",
    category: "SWAP_STATE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["swap", "chaos"],
    trigger: { on: "OWN_TURN" },
    target: "ALL_PLAYERS",
    effects: [{ kind: "SWAP_STATE", between: ["HIGHEST_FATE", "LOWEST_FATE"], what: "TEMP_STATUS" }],
  },
  {
    id: "SWAP_STATE_10",
    category: "SWAP_STATE",
    type: "ACTIVE",
    maxUses: 1,
    copyable: true,
    tags: ["status", "restore"],
    trigger: { on: "OWN_TURN" },
    target: "SELF",
    effects: [{ kind: "ROLLBACK_STATE", who: "SELF", to: "LAST_ROUND_END" }],
  },
];
